SELECT C2.COURSENO+C2.[GROUP] COURSENO, C.COURSENAME,C.CREDITS,C.HOURS,C.EXPERIMENTS,C.COMPUTING,C3.CLASSNO,C3.CLASSNAME,COUNT(*) [COUNT] 
FROM COURSES C
	INNER JOIN COURSEPLAN C2 ON (C2.COURSENO = C.COURSENO)
	INNER JOIN CLASSES C3 ON (C2.CLASSNO=C3.CLASSNO)
	INNER JOIN SCORES S ON (S.[YEAR]=:S_YEAR AND S.TERM=:S_TERM AND C2.COURSENO=S.COURSENO and C2.[GROUP]=S.[GROUP])
WHERE C2.[YEAR] = :YEAR AND C2.TERM =:TERM AND (COURSENAME LIKE '%实习%' OR COURSENAME LIKE '%设计%') AND C.SCHOOL LIKE :SCHOOL
GROUP BY C2.COURSENO+C2.[GROUP],COURSENAME,CREDITS,HOURS,EXPERIMENTS,COMPUTING ,C3.CLASSNO,C3.CLASSNAME 
ORDER BY COURSENO