SELECT SCHOOL,SCHOOLNAME,COURSETYPE, COUNT(*) [COUNT] FROM 
(SELECT DISTINCT YEAR,TERM,SCHOOL,SCHOOLNAME,COURSETYPE,COURSENO,[GROUP],C.NAME FROM VIEWSCHEDULE V,COURSEAPPROACHES C WHERE C.VALUE=V.COURSETYPE) TJ 
WHERE YEAR =:YEAR  AND TERM =:TERM AND SCHOOL LIKE :SCHOOL AND NAME like :COURSETYPE 
GROUP BY SCHOOL,SCHOOLNAME,COURSETYPE 
ORDER BY SCHOOL