SELECT DISTINCT C.COURSENO,C.COURSENAME,C.CREDITS,C.HOURS,C.EXPERIMENTS,C.COMPUTING FROM COURSES C, SCHEDULEPLAN S 
WHERE YEAR = :YEAR AND TERM =:TERM AND S.COURSENO = C.COURSENO AND (EXPERIMENTS > 0 OR COMPUTING > 0) AND LEFT(C.COURSENO, 2) LIKE :SCHOOL 
ORDER BY C.COURSENO