SELECT VALUE,COUNT(*) [COUNT] FROM (SELECT DISTINCT YEAR,TERM,SCHOOL,SCHOOLNAME,COURSENO+[GROUP] COURSENO,C.VALUE,C.NAME 
FROM VIEWSCHEDULE V,COURSETYPEOPTIONS C WHERE V.TYPE = C.NAME) TJ 
WHERE YEAR = :YEAR  AND TERM = :TERM 
GROUP BY VALUE