SELECT COUNT(*) [COUNT] FROM (SELECT SCHOOL,SCHOOLNAME,VALUE FROM 
(SELECT DISTINCT YEAR,TERM,SCHOOL,SCHOOLNAME,COURSENO+[GROUP] COURSENO,C.VALUE,C.NAME FROM VIEWSCHEDULE V,COURSETYPEOPTIONS C WHERE V.TYPE = C.NAME) TJ
WHERE YEAR = :YEAR AND TERM = :TERM AND SCHOOL LIKE :SCHOOL AND NAME like :NAME 
GROUP BY SCHOOL,SCHOOLNAME,VALUE) TJ 