SELECT COUNT(*) [COUNT] FROM 
(SELECT SCHOOL FROM (SELECT DISTINCT YEAR,TERM,SCHOOL,SCHOOLNAME,COURSETYPE,C.NAME FROM VIEWSCHEDULE V,COURSEAPPROACHES C WHERE C.VALUE=V.COURSETYPE) TJ 
WHERE YEAR =:YEAR  AND TERM =:TERM AND SCHOOL LIKE :SCHOOL AND NAME like :COURSETYPE GROUP BY SCHOOL, SCHOOLNAME, COURSETYPE) TJ