SELECT COUNT(*) FROM KQABSENT K 
LEFT JOIN STUDENTS S ON S.STUDENTNO=K.STUDENTNO 
LEFT JOIN CLASSES C ON C.CLASSNO=S.CLASSNO 
LEFT JOIN SCHOOLS SCH ON SCH.SCHOOL=C.SCHOOL 
WHERE K.[YEAR]=:YEAR AND K.TERM=:TERM AND SCH.SCHOOL LIKE :SCHOOL AND K.STUDENTNO LIKE :STUDENTNO  AND K.DAY LIKE :DAY
AND K.TIME LIKE :TIME AND K.TYPE LIKE :TYPE AND K.COURSENO LIKE :COURSENO