SELECT KQ.STUDENTNO,S.NAME NAME,KQ.YEAR,KQ.TERM,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND K.STUDENTNO=KQ.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=1) WEEK1,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=2) WEEK2,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=3) WEEK3,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=4) WEEK4,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=5) WEEK5,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=6) WEEK6,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=7) WEEK7,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=8) WEEK8,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=9) WEEK9,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=10) WEEK10,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=11) WEEK11,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=12) WEEK12,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=13) WEEK13,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=14) WEEK14,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=15) WEEK15,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=16) WEEK16,
	(SELECT COUNT(*) FROM KQABSENT K WHERE K.YEAR=KQ.YEAR AND K.TERM =KQ.TERM AND K.COURSENO=KQ.COURSENO 
	AND KQ.STUDENTNO=K.STUDENTNO AND K.TYPE=KQ.TYPE AND K.WEEK=17) WEEK17 
FROM KQABSENT KQ INNER JOIN STUDENTS S ON S.STUDENTNO=KQ.STUDENTNO 
WHERE KQ.YEAR=:YEAR AND KQ.TERM =:TERM AND KQ.COURSENO=:COURSENO AND KQ.TYPE=:TYPE 
GROUP BY KQ.STUDENTNO,S.NAME,KQ.YEAR,KQ.TERM,KQ.COURSENO,KQ.TYPE
ORDER BY KQ.STUDENTNO DESC