SELECT K.RECNO,K.YEAR,K.TERM,K.COURSENO,C.COURSENAME,K.STUDENTNO,S.NAME,K.WEEK,K.DAY, T.VALUE [TIME],CONVERT(varchar(10), K.DATE, 23) DATE,
CASE WHEN K.TYPE = 'A' THEN '缺课' WHEN K.TYPE = 'D' THEN '到课' END AS TYPE 
FROM KQABSENT K INNER JOIN TIMESECTIONS T ON K.TIME=T.NAME 
LEFT JOIN COURSES C ON C.COURSENO=SUBSTRING(K.COURSENO,1,7) 
LEFT JOIN STUDENTS S ON S.STUDENTNO=K.STUDENTNO 
LEFT JOIN CLASSES C2 ON C2.CLASSNO=S.CLASSNO 
LEFT JOIN SCHOOLS SCH ON SCH.SCHOOL=C2.SCHOOL 
WHERE K.[YEAR]=:YEAR AND K.TERM=:TERM AND SCH.SCHOOL LIKE :SCHOOL AND K.STUDENTNO LIKE :STUDENTNO  AND K.DAY LIKE :DAY 
AND K.TIME LIKE :TIME AND K.TYPE LIKE :TYPE AND K.COURSENO LIKE :COURSENO ORDER BY K.RECNO DESC