SELECT K.STUDENTNO,STUDENTS.NAME,CLASSES.CLASSNAME,SCHOOLS.NAME SCHOOLNAME,COUNT(*) [COUNT],K.[YEAR],K.TERM 
FROM KQABSENT K INNER JOIN STUDENTS ON STUDENTS.STUDENTNO=K.STUDENTNO 
INNER JOIN CLASSES ON CLASSES.CLASSNO=STUDENTS.CLASSNO 
INNER JOIN SCHOOLS ON SCHOOLS.SCHOOL=CLASSES.SCHOOL 
WHERE K.[YEAR]=:YEAR AND K.TERM=:TERM AND K.TYPE='A' 
GROUP BY K.STUDENTNO,STUDENTS.NAME,CLASSES.CLASSNAME,SCHOOLS.NAME,K.[YEAR],K.TERM 
HAVING COUNT(*) > :COUNT 
ORDER BY [COUNT] DESC