SELECT S.STUDENTNO,S.NAME,S4.NAME AS SEX,CONVERT(varchar(10), S.ENTERDATE, 23) ENTERDATE,S.YEARS,S.CLASSNO,C.CLASSNAME,S.WARN,S3.[VALUE] STATUS,
	CONVERT(varchar(10), P.BIRTHDAY, 23) BIRTHDAY,N.NAME AS NATIONALITY,P2.NAME AS PARTY,P.POSTCODE,P.ADDRESS,P.TEL,P.SCORE,P.MIDSCHOOL,P.ID 
FROM STUDENTS S LEFT JOIN PERSONAL P ON S.STUDENTNO = P.STUDENTNO 
	LEFT JOIN NATIONALITYCODE N ON P.NATIONALITY = N.CODE 
	LEFT JOIN PARTYCODE P2 ON P.PARTY = P2.CODE 
	LEFT JOIN CLASSES C ON S.CLASSNO = C.CLASSNO 
	LEFT JOIN STATUSOPTIONS S3 ON S.STATUS = S3.NAME 
	LEFT JOIN SEXCODE S4 ON S.SEX = S4.CODE 
WHERE RTRIM(S.STUDENTNO) LIKE :STUDENTNO AND S.NAME LIKE :NAME AND S.CLASSNO LIKE :CLASSNO AND S.SCHOOL LIKE :SCHOOL AND S.STATUS LIKE :STATUS  
ORDER BY ENTERDATE DESC