delete from r28
from r28 inner join students on students.studentno=r28.studentno
where r28.programno=:D_PROGRAMNO AND students.CLASSNO=:D_CLASSNO;

INSERT INTO R28
SELECT STUDENTS.STUDENTNO AS STUDENTNO,R16.PROGRAMNO AS PROGRAMNO
FROM CLASSES
JOIN STUDENTS ON CLASSES.CLASSNO=STUDENTS.CLASSNO
JOIN R16 ON CLASSES.CLASSNO=R16.CLASSNO
WHERE R16.PROGRAMNO=:I_PROGRAMNO
AND CLASSES.CLASSNO=:I_CLASSNO