select COUNT(courses.CourseNo) AS ROWS
from courses
JOIN Schools ON COURSES.SCHOOL=SCHOOLS.SCHOOL
JOIN COURSETYPEOPTIONS ON COURSES.TYPE=COURSETYPEOPTIONS.NAME
where
Courses.CourseNo like :COURSENO
and Courses.CourseName like :COURSENAME
and Courses.School like :SCHOOL
AND COURSETYPEOPTIONS.NAME LIKE :COURSETYPE

