INSERT INTO R28
SELECT R4.STUDENTNO AS STUDENTNO,PROGRAMS.PROGRAMNO AS PROGRAMNO
FROM PROGRAMS,SUBSIDIARIES,R4
WHERE PROGRAMS.PROGRAMNO=:PROGRAMNO
AND SUBSIDIARIS.CLASSNO=R4.CLASSNO
AND SUBSIDIARIS.CLASSNO=:CLASSNO