SELECT S.RECNO,S.[YEAR],S.TERM,S.[周数] WEEK,CONVERT(varchar(10), S.[上课时间], 23) DATETIME,TIMESECTORS.[VALUE] TIMENO,S.COURSENO,COURSES.COURSENAME,
SCHOOLS.NAME SCHOOLNAME,S.STUDENTNO,STUDENTS.NAME STUDENTNAME,STUDENTS.CLASSNO,CLASSES.CLASSNAME,S.[学时] TIMENUM,S2.NAME REASON,S.[备注] BREAKTHERULE 
FROM 学生考勤表 S INNER JOIN COURSES ON LEFT(S.COURSENO,7) = COURSES.COURSENO INNER JOIN STUDENTS ON S.STUDENTNO = STUDENTS.STUDENTNO 
INNER JOIN 学生考勤表请假理由OPTIONS S2 ON S.请假理由 = S2.CODE INNER JOIN CLASSES ON STUDENTS.CLASSNO = CLASSES.CLASSNO 
INNER JOIN TIMESECTORS ON TIMESECTORS.NAME=S.节次 INNER JOIN SCHOOLS ON SCHOOLS.SCHOOL=COURSES.SCHOOL 
WHERE S.[YEAR] = :YEAR AND  S.TERM = :TERM AND S.STUDENTNO LIKE :STUDENTNO AND STUDENTS.NAME LIKE :NAME AND S.COURSENO LIKE :COURSENO 
AND S.[周数] LIKE :WEEK AND STUDENTS.SCHOOL LIKE :SCHOOL  ORDER BY S.RECNO DESC