SELECT COUNT(*) FROM [学生考勤表] S 
WHERE S.[YEAR] LIKE :YEAR AND S.TERM LIKE :TERM AND S.STUDENTNO LIKE :STUDENTNO AND S.STUDENTNO IN 
(SELECT STU.STUDENTNO FROM STUDENTS STU WHERE STU.NAME LIKE :NAME) AND 
S.COURSENO LIKE :COURSENO AND S.[周数] LIKE :WEEK AND S.STUDENTNO IN 
(SELECT STU.STUDENTNO FROM STUDENTS STU WHERE STU.SCHOOL LIKE :SCHOOL)