SELECT 学生考勤表.STUDENTNO STUDENTNO, STUDENTS.NAME STUDENTNAME,CLASSES.CLASSNAME CLASSNAME,STR(SUM(学时 * BASE),10,2) [SUM],SCHOOLS.NAME SCHOOLSNAME 
FROM 学生考勤表 INNER JOIN (SELECT RECNO,CASE [请假理由] WHEN 'A' THEN 1 WHEN 'D' THEN 0.33 WHEN 'E' THEN 0.33 ELSE 0 END AS BASE FROM 学生考勤表) 
	KAOQIN ON KAOQIN.RECNO = 学生考勤表.RECNO INNER JOIN STUDENTS ON STUDENTS.STUDENTNO=学生考勤表.STUDENTNO INNER JOIN SCHOOLS ON 
	STUDENTS.SCHOOL=SCHOOLS.SCHOOL INNER JOIN CLASSES ON CLASSES.CLASSNO=STUDENTS.CLASSNO 
WHERE  学生考勤表.YEAR=:YEAR AND TERM=:TERM AND STUDENTS.SCHOOL
LIKE :SCHOOL AND EXISTS (SELECT * FROM COURSES WHERE COURSES.COURSENO=SUBSTRING(学生考勤表.COURSENO,1,7)) 
GROUP BY 学生考勤表.STUDENTNO,STUDENTS.NAME,CLASSES.CLASSNAME,SCHOOLS.NAME HAVING SUM(学时 * BASE) BETWEEN :START AND :END ORDER BY [SUM] DESC