SELECT A.YEAR,A.TEACHERNO,A.TSCORE,A.XSCORE,A.ADDSCORE,RTRIM(A.REM) REM,B.NAME AS TEACHERNAME,B.SCHOOL,C.NAME AS SCHHOLNAME
FROM 教学质量评估院校评估 AS A
INNER JOIN TEACHERS AS B ON B.TEACHERNO=A.TEACHERNO
INNER JOIN SCHOOLS AS C ON B.SCHOOL=C.SCHOOL
WHERE A.YEAR=:YEAR AND B.SCHOOL=:SCHOOLNO