SELECT TEACHERS.NAME AS TEACHERNAME,教学质量评估综合.TEACHERNO AS TEACHERNO,
教学质量评估综合.COURSENO AS COURSENO,COURSES.COURSENAME AS COURSENAME,
case[TASK]
WHEN 'K' THEN '理论课'
WHEN 'S' THEN '实践课'
WHEN 'B' THEN '毕业实践'
WHEN 'C' THEN '理实一体'
ELSE '未知' END AS TASK,教学质量评估综合.YEAR,教学质量评估综合.TERM,教学质量评估综合.RECNO,count(教学质量评估详细.studentno) AS STUDENTCOUNT
FROM 教学质量评估综合 INNER JOIN TEACHERS ON TEACHERS.TEACHERNO=教学质量评估综合.TEACHERNO
INNER JOIN COURSES ON COURSES.COURSENO=SUBSTRING(教学质量评估综合.COURSENO,1,7)
LEFT OUTER  JOIN 教学质量评估详细 ON 教学质量评估详细.map=教学质量评估综合.recno
WHERE 教学质量评估综合.YEAR=:YEAR AND 教学质量评估综合.TERM=:TERM AND TEACHERS.NAME LIKE :TEACHERNAME
AND 教学质量评估综合.courseno LIKE :COURSENO AND COURSES.COURSENAME LIKE :COURSENAME
AND 教学质量评估综合.task like :TASK
GROUP BY TEACHERS.NAME,教学质量评估综合.TEACHERNO,教学质量评估综合.COURSENO,COURSENAME,
教学质量评估综合.TASK,教学质量评估综合.YEAR,教学质量评估综合.TERM,教学质量评估综合.RECNO


