SELECT S.STUDENTNO,S.NAME,C.CLASSNAME,S2.NAME SCHOOLNAME,S3.[VALUE] FROM STUDENTS S 
INNER JOIN CLASSES C ON S.CLASSNO=C.CLASSNO 
INNER JOIN SCHOOLS S2 ON S2.SCHOOL=S.SCHOOL 
INNER JOIN STATUSOPTIONS S3 ON S3.NAME=S.STATUS WHERE C.CLASSNO=:CLASSNO