INSERT INTO WORKLOADCALC(YEAR,TERM,COURSENO,[GROUP],TOTAL,HOURS,WEEKS,ATTENDENTS,STANDARD,WORKTYPE,CLASSCOEFF,CORRECTCOEFF,COURSETYPE,ALLOCWORKLOAD,MAP)
SELECT DISTINCT SP.[YEAR],SP.TERM,SP.COURSENO,SP.[GROUP],
CASE WHEN W.HOURS IS NULL THEN C.TOTAL ELSE W.HOURS END AS TOTAL,SP.HOURS,
CASE WHEN W.WEEKS IS NULL THEN 17 ELSE W.WEEKS END AS WEEKS,
SP.ATTENDENTS,C.STANDARD,W.WORKTYPE,
CASE WHEN SP.ATTENDENTS > 0 AND W.WORKTYPE='M1' THEN
	CAST((1+(CAST(SP.ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(SP.ATTENDENTS AS DECIMAL(10,3))) AS DECIMAL(10,2))
ELSE 0 END AS CLASSCOEFF,
CASE WHEN W.WORKTYPE='M1' THEN
	CASE
		WHEN CAST(SP.ATTENDENTS AS INT)=0 THEN CASE WHEN RTRIM(CP.COURSETYPE)='M' OR RTRIM(CP.COURSETYPE)='T' THEN 1 ELSE 0.9 END
		WHEN (RTRIM(CP.COURSETYPE)='M' OR RTRIM(CP.COURSETYPE)='T') AND  CAST((1+(CAST(SP.ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(SP.ATTENDENTS AS DECIMAL(10,3)))AS DECIMAL(10,2))<1 THEN 1
		WHEN CAST((1+(CAST(SP.ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(SP.ATTENDENTS AS DECIMAL(10,3)))AS DECIMAL(10,2))<0.9 THEN 0.9
		WHEN CAST((1+(CAST(SP.ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(SP.ATTENDENTS AS DECIMAL(10,3)))AS DECIMAL(10,2))>1.6 THEN 1.6
	ELSE
		CAST((1+(CAST(SP.ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(SP.ATTENDENTS AS DECIMAL(10,3))) AS DECIMAL(10,2))
  END
ELSE 0 END CORRECTCOEFF,CP.COURSETYPE,0,SP.RECNO
FROM SCHEDULEPLAN SP
LEFT JOIN COURSES C ON C.COURSENO=SP.COURSENO
LEFT JOIN WORKLOADPARAM W ON W.COURSENO=SP.COURSENO
LEFT JOIN COURSEPLAN CP ON CP.COURSENO=SP.COURSENO AND CP.[YEAR]=SP.[YEAR] AND CP.TERM=SP.TERM AND CP.[GROUP]=SP.[GROUP]
WHERE C.COURSENAME IS NOT NULL AND W.WORKTYPE IS NOT NULL AND SP.YEAR=:YEAR AND SP.TERM =:TERM AND C.SCHOOL LIKE :SCHOOL