SELECT RTRIM(T.TEACHERNO) TEACHERNO,T.NAME,S.NAME SCHOOLNAME
FROM TEACHERS T
LEFT JOIN SCHOOLS S ON S.SCHOOL=T.SCHOOL 
WHERE T.NAME LIKE :NAME AND T.TEACHERNO LIKE :TEACHERNO AND S.SCHOOL LIKE :SCHOOL 
AND NOT EXISTS(SELECT * FROM WORKLOADALLOC W WHERE W.TEACHERNO=T.TEACHERNO AND W.CALCID=:ID)
ORDER BY SCHOOLNAME