UPDATE WORKLOADCALC SET WORKLOAD=(
SELECT
CASE
	WHEN WORKTYPE='M1' THEN
		CASE WHEN COURSETYPE='E' THEN CAST((TOTAL*CORRECTCOEFF*1.2) AS DECIMAL(10,2)) ELSE CAST((TOTAL*CORRECTCOEFF) AS DECIMAL(10,2)) END
  WHEN WORKTYPE='M21' OR WORKTYPE='M22'
		THEN CAST((TOTAL*0.5) AS DECIMAL(10,2))
  WHEN WORKTYPE='M23'
		THEN CAST((ATTENDENTS*W.WEEKS*0.15) AS DECIMAL(10,2))
	WHEN WORKTYPE='M3'
		THEN CAST((ATTENDENTS*2) AS DECIMAL(10,2))
	WHEN WORKTYPE='M4'
    THEN CAST((TOTAL*2) AS DECIMAL(10,2))
  WHEN WORKTYPE='M5'
    THEN CAST((ATTENDENTS*1.2) AS DECIMAL(10,2))
	WHEN WORKTYPE='M6'
		THEN CAST((0.5*(SELECT COUNT(*) FROM WORKLOADCALC W2 WHERE W2.[YEAR]=W.[YEAR] AND W2.TERM=W.TERM AND W2.COURSENO=W.COURSENO)) AS DECIMAL(10,2))
	WHEN WORKTYPE='M7'
	  THEN CAST((0.05*(SELECT COUNT(*) FROM STUDENTS WHERE STATUS='A')) AS DECIMAL(10,2))
  WHEN WORKTYPE='M8'
		THEN CAST((ATTENDENTS/STANDARD*TOTAL) AS DECIMAL(10,2))
  WHEN WORKTYPE='M9'
		THEN CAST((ATTENDENTS/STANDARD*TOTAL*2) AS DECIMAL(10,2))
	ELSE TOTAL END AS WORKLOAD FROM WORKLOADCALC AS W WHERE WORKLOADCALC.ID=W.ID
) WHERE ID=:ID