UPDATE WORKLOADCALC SET CLASSCOEFF=( 
SELECT CASE WHEN ATTENDENTS > 0 AND WORKTYPE='M1' THEN
	CAST((1+(CAST(ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(ATTENDENTS AS DECIMAL(10,3))) AS DECIMAL(10,2)) 
ELSE 0 END CLASSCOEFF
FROM WORKLOADCALC W WHERE WORKLOADCALC.ID=W.ID),
CORRECTCOEFF=(SELECT CASE WHEN WORKTYPE='M1' THEN
	CASE 
		WHEN CAST(ATTENDENTS AS INT)=0 THEN CASE WHEN RTRIM(COURSETYPE)='M' OR RTRIM(COURSETYPE)='T' THEN 1 ELSE 0.9 END
		WHEN (RTRIM(COURSETYPE)='M' OR RTRIM(COURSETYPE)='T') AND  CAST((1+(CAST(ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(ATTENDENTS AS DECIMAL(10,3)))AS DECIMAL(10,2))<1 THEN 1
		WHEN CAST((1+(CAST(ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(ATTENDENTS AS DECIMAL(10,3)))AS DECIMAL(10,2))<0.9 THEN 0.9
		WHEN CAST((1+(CAST(ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(ATTENDENTS AS DECIMAL(10,3)))AS DECIMAL(10,2))>1.6 THEN 1.6
	ELSE 
		CAST((1+(CAST(ATTENDENTS AS DECIMAL(10,3))-CAST(STANDARD AS DECIMAL(10,3)))/CAST(ATTENDENTS AS DECIMAL(10,3))) AS DECIMAL(10,2)) 
  END 
ELSE 0 END CORRECTCOEFF
FROM WORKLOADCALC W WHERE WORKLOADCALC.ID=W.ID)
WHERE ID=:ID