insert INTO TIMELIST SELECT :SR_YEAR,:SR_TERM,:SR_ROOMNO,'R','',0,0,0,0,0,0,0
WHERE NOT EXISTS (SELECT * from TIMELIST WHERE [YEAR]=:IR_YEAR AND TERM=:IR_TERM AND TYPE='R' AND WHO=:IR_ROOMNO);

insert INTO TIMELIST SELECT :SC_YEAR,:SC_TERM,:SC_CLASSNO,'C','',0,0,0,0,0,0,0
WHERE NOT EXISTS (SELECT * from TIMELIST WHERE [YEAR]=:IC_YEAR AND TERM=:IC_TERM AND TYPE='C' AND WHO=:IC_CLASSNO);

insert INTO TIMELIST SELECT :ST_YEAR,:ST_TERM,:ST_TEACHNO,'T','',0,0,0,0,0,0,0
WHERE NOT EXISTS (SELECT * from TIMELIST WHERE [YEAR]=:IT_YEAR AND TERM=:IT_TERM AND TYPE='T' AND WHO=:IT_TEACHNO);

insert INTO TIMELIST SELECT :SP_YEAR,:SP_TERM,:SP_COURSENO,'P',:SP_GROUP,0,0,0,0,0,0,0
WHERE NOT EXISTS (SELECT * from TIMELIST WHERE [YEAR]=:IP_YEAR AND TERM=:IP_TERM AND TYPE='P' AND RTRIM(TIMELIST.WHO)+RTRIM(TIMELIST.PARA)=:IP_COURSENO);

update SCHEDULE set [DAY]=:DAY,[TIME]=:TIME,ROOMNO=:ROOMNO,UNIT=:UNIT,OEW=:OEW where RECNO=:RECNO;
UPDATE TIMELIST set MON=:R_MON,TUE=:R_TUE,WES=:R_WES,THU=:R_THU,FRI=:R_FRI,SAT=:R_SAT,SUN=:R_SUN where [YEAR]=:R_YEAR AND TERM=:R_TERM AND [TYPE]='R' AND WHO=:R_ROOMNO;
UPDATE TIMELIST set MON=:C_MON,TUE=:C_TUE,WES=:C_WES,THU=:C_THU,FRI=:C_FRI,SAT=:C_SAT,SUN=:C_SUN where [YEAR]=:C_YEAR AND TERM=:C_TERM AND [TYPE]='C' AND WHO=:C_CLASSNO;
UPDATE TIMELIST set MON=:T_MON,TUE=:T_TUE,WES=:T_WES,THU=:T_THU,FRI=:T_FRI,SAT=:T_SAT,SUN=:T_SUN where [YEAR]=:T_YEAR AND TERM=:T_TERM AND [TYPE]='T' AND WHO=:T_TEACHNO;
UPDATE TIMELIST set MON=:P_MON,TUE=:P_TUE,WES=:P_WES,THU=:P_THU,FRI=:P_FRI,SAT=:P_SAT,SUN=:P_SUN where [YEAR]=:P_YEAR AND TERM=:P_TERM AND [TYPE]='P' AND RTRIM(TIMELIST.WHO)+RTRIM(TIMELIST.PARA)=:P_COURSENO;