exec sp_executesql N'SELECT DISTINCT(RTRIM(TEACHERS.TEACHERNO)) AS TEACHERNO
FROM TEACHERS JOIN TEACHERPLAN ON TEACHERS.TEACHERNO=TEACHERPLAN.TEACHERNO
JOIN SCHEDULE ON TEACHERPLAN.RECNO=SCHEDULE.MAP
WHERE SCHEDULE.YEAR=@P1 AND SCHEDULE.TERM=@P2
ORDER BY TEACHERNO
',N'@P1 varchar(4),@P2 smallint','2014',1

exec sp_executesql N'SELECT SCHEDULE.COURSENO+SCHEDULE.[GROUP] AS COURSE,
SCHEDULE.DAY,SCHEDULE.TIME,SCHEDULE.OEW,SCHEDULE.WEEKS
FROM SCHEDULE JOIN TEACHERPLAN
ON SCHEDULE.MAP=TEACHERPLAN.RECNO
WHERE SCHEDULE.YEAR=@P1
AND SCHEDULE.TERM=@P2
AND TEACHERPLAN.TEACHERNO=@P3
',N'@P1 varchar(4),@P2 smallint,@P3 varchar(6)','2013',1,'012104'

exec sp_executesql N'UPDATE TIMELIST
SET MON=@P1,TUE=@P2,WES=@P3,THU=@P4,FRI=@P5,SAT=@P6,SUN=@P7
WHERE YEAR=@P8
AND TERM=@P9
AND TYPE=@P10
AND WHO=@P11
AND PARA=@P12
',N'@P1 int,@P2 int,@P3 int,@P4 int,@P5 int,@P6 int,@P7 int,@P8 varchar(4),@P9 varchar(16),@P10 varchar(1),@P11 varchar(10),@P12 varchar(2)',
0,0,0,0,0,0,0,'2013','1','T','012104',''



exec sp_executesql N'SELECT DISTINCT(RTRIM(CLASSES.CLASSNO)) AS CLASSNO
FROM CLASSES JOIN COURSEPLAN ON CLASSES.CLASSNO=COURSEPLAN.CLASSNO
WHERE COURSEPLAN.YEAR=@P1 AND COURSEPLAN.TERM=@P2
ORDER BY CLASSNO
',N'@P1 varchar(4),@P2 smallint','2014',1


exec sp_executesql N'SELECT SCHEDULE.COURSENO+SCHEDULE.[GROUP] AS COURSE,
SCHEDULE.DAY,SCHEDULE.TIME,SCHEDULE.OEW,SCHEDULE.WEEKS
FROM SCHEDULE JOIN COURSEPLAN
ON  SCHEDULE.YEAR=COURSEPLAN.YEAR
AND SCHEDULE.TERM=COURSEPLAN.TERM
AND SCHEDULE.[GROUP]=COURSEPLAN.[GROUP]
AND SCHEDULE.COURSENO=COURSEPLAN.COURSENO
WHERE COURSEPLAN.CLASSNO=@P1
AND SCHEDULE.YEAR=@P2
AND SCHEDULE.TERM=@P3
',N'@P1 varchar(7),@P2 varchar(4),@P3 smallint','000002','2014',1

exec sp_executesql N'UPDATE TIMELIST
SET MON=@P1,TUE=@P2,WES=@P3,THU=@P4,FRI=@P5,SAT=@P6,SUN=@P7
WHERE YEAR=@P8
AND TERM=@P9
AND TYPE=@P10
AND WHO=@P11
AND PARA=@P12
',N'@P1 int,@P2 int,@P3 int,@P4 int,@P5 int,@P6 int,@P7 int,@P8 varchar(4),@P9 varchar(16),@P10 varchar(1),@P11 varchar(10),@P12 varchar(2)
',0,0,0,0,0,0,0,'2014','1','C','000002',''


exec sp_executesql N'SELECT DISTINCT(COURSENO+[GROUP]) AS COURSENOGROUP
FROM SCHEDULE
WHERE YEAR=@P1 AND TERM=@P2
ORDER BY COURSENOGROUP
',N'@P1 varchar(4),@P2 smallint','2014',1

exec sp_executesql N'SELECT DISTINCT(RTRIM(CLASSROOMS.ROOMNO)) AS ROOMNO
FROM CLASSROOMS JOIN SCHEDULE
ON CLASSROOMS.ROOMNO=SCHEDULE.ROOMNO
WHERE SCHEDULE.YEAR=@P1 AND TERM=@P2
ORDER BY ROOMNO
',N'@P1 varchar(4),@P2 smallint','2014',1