SELECT distinct RTRIM(WHO)+RTRIM(PARA) AS WHO,COURSES.COURSENAME AS WHOSNAME,TIMELIST.TYPE,MON,TUE,WES,THU,FRI,SAT,SUN FROM TIMELIST
JOIN COURSES ON RTRIM(COURSES.COURSENO)=RTRIM(TIMELIST.WHO)
WHERE TIMELIST.TYPE='P' AND TIMELIST.YEAR=:YEAR AND TIMELIST.TERM=:TERM AND RTRIM(TIMELIST.WHO)+RTRIM(TIMELIST.PARA) IN (:COURSENO)