SELECT distinct RTRIM(WHO) AS WHO,TEACHERS.NAME AS WHOSNAME,TIMELIST.TYPE,MON,TUE,WES,THU,FRI,SAT,SUN FROM TIMELIST
INNER JOIN TEACHERPLAN ON TIMELIST.YEAR=TEACHERPLAN.YEAR AND TEACHERPLAN.TERM=TIMELIST.TERM AND RTRIM(TEACHERPLAN.TEACHERNO)=RTRIM(TIMELIST.WHO)
INNER JOIN TEACHERS ON RTRIM(TIMELIST.WHO)=RTRIM(TEACHERS.TEACHERNO)
INNER JOIN SCHEDULE ON SCHEDULE.MAP=TEACHERPLAN.RECNO
WHERE TIMELIST.TYPE='T'

AND TIMELIST.YEAR=:YEAR AND TIMELIST.TERM=:TERM AND SCHEDULE.COURSENO+SCHEDULE.[GROUP] IN (:COURSENO)
order by WHO