

SELECT
dbo.getOne(SCHEDULE.COURSENO)+dbo.getOne(SCHEDULE.[GROUP]) AS COURSE,
dbo.getOne(COURSES.COURSENAME) as COURSENAME,
dbo.getOne(SCHEDULE.DAY) as [DAY],
dbo.getOne(SCHEDULE.TIME) as [TIME],
dbo.getOne(TIMESECTORS.VALUE) AS TIMENAME,
dbo.getOne(SCHEDULE.ROOMNO) as ROOMNO,
dbo.getOne(TEACHERPLAN.HOURS) as [HOURS],
dbo.getOne(SCHEDULEPLAN.WEEKS) as WEEKS,
dbo.getOne(SCHEDULE.MAP) as MAP,
dbo.getOne(CLASSROOMS.SEATS) as SEATS,
dbo.getOne(CLASSROOMS.USAGE) as [USAGE],
dbo.getOne(CLASSROOMS.JSN) AS ROOMNAME,
dbo.getOne(TEACHERPLAN.TEACHERNO) as TEACHERNO,
dbo.getOne(TEACHERS.NAME) AS TEACHERNAME,
dbo.getOne(SCHEDULE.OEW) AS OEW,
dbo.getOne(OEWOPTIONS.NAME) AS WEEKNAME,
dbo.getOne(SCHEDULE.LE) AS TASK,
dbo.getOne(TASKOPTIONS.NAME) AS TASKNAME,
dbo.getOne(SCHEDULEPLAN.ESTIMATE) as ESTIMATE,
dbo.getOne(SCHEDULE.RECNO) as RECNO,
dbo.getOne(SCHEDULE.UNIT) as UNIT,
dbo.getOne(UNITOPTIONS.NAME) AS UNITNAME,
dbo.getOne(SCHEDULE.TIMER) as TIMER,
dbo.getOne(TIMESECTIONS.VALUE) AS TIMEREQUEST,
dbo.getOne(SCHEDULE.ROOMR) as ROOMR,
dbo.getOne(SCHEDULEPLAN.AREA) as AREA,
dbo.getOne(ROOMOPTIONS.VALUE) as ROOMEQUIPMENT,
dbo.getOne(ROOMOPTIONS.NAME) as ROOMR2,
dbo.getOne(COURSES.SCHOOL) as SCHOOL,
dbo.getOne(SCHOOLS.NAME) as SCHOOLNAME,
dbo.GROUP_CONCAT_MERGE(CLASSES.CLASSNO +'('+RTRIM(CLASSES.CLASSNAME)+')', ',') AS CLASSNAME,
dbo.GROUP_CONCAT_MERGE(CLASSES.CLASSNO,',') as CLASSNO,
dbo.GROUP_CONCAT_MERGE(CLASSES.CLASSNO+'-'+RTRIM(CLASSES.CLASSNAME),',') AS CLASSNO2,
cast(dbo.getOne(TIMESECTORS.TIMEBITS) as int) as TIMES
FROM SCHEDULEPLAN
JOIN TEACHERPLAN ON SCHEDULEPLAN.RECNO=TEACHERPLAN.MAP
JOIN SCHEDULE ON (TEACHERPLAN.RECNO=SCHEDULE.MAP)
JOIN COURSEPLAN ON (SCHEDULE.COURSENO=COURSEPLAN.COURSENO AND SCHEDULE.[GROUP]=COURSEPLAN.[GROUP] AND SCHEDULE.YEAR=COURSEPLAN.YEAR AND SCHEDULE.TERM=COURSEPLAN.TERM)
JOIN CLASSES ON (COURSEPLAN.CLASSNO=CLASSES.CLASSNO)
LEFT OUTER JOIN TIMESECTORS ON SCHEDULE.TIME=TIMESECTORS.NAME
LEFT OUTER JOIN COURSES ON SCHEDULE.COURSENO=COURSES.COURSENO
LEFT OUTER JOIN SCHOOLS ON COURSES.SCHOOL=SCHOOLS.SCHOOL
LEFT OUTER JOIN TASKOPTIONS ON (SCHEDULE.LE=TASKOPTIONS.CODE)
LEFT OUTER JOIN ROOMOPTIONS ON (SCHEDULE.ROOMR=ROOMOPTIONS.NAME)
LEFT OUTER JOIN TEACHERS ON TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
LEFT OUTER JOIN TIMESECTIONS ON SCHEDULE.TIMER=TIMESECTIONS.NAME
LEFT OUTER JOIN UNITOPTIONS ON SCHEDULE.UNIT=UNITOPTIONS.CODE
LEFT OUTER JOIN CLASSROOMS ON SCHEDULE.ROOMNO=CLASSROOMS.ROOMNO
LEFT OUTER JOIN OEWOPTIONS ON SCHEDULE.OEW=OEWOPTIONS.CODE
WHERE SCHEDULEPLAN.YEAR=:YEAR AND SCHEDULEPLAN.TERM=:TERM
AND (SCHEDULEPLAN.COURSENO+SCHEDULEPLAN.[GROUP] IN (:COURSENO))
GROUP BY SCHEDULE.COURSENO, SCHEDULE.[GROUP], SCHEDULE.RECNO
ORDER BY SCHEDULE.COURSENO,SCHEDULE.[GROUP]


/*
SELECT
SCHEDULE.COURSENO+SCHEDULE.[GROUP] AS COURSE,
COURSES.COURSENAME,
SCHEDULE.DAY,
SCHEDULE.TIME,
TIMESECTORS.VALUE AS TIMENAME,
SCHEDULE.ROOMNO,
TEACHERPLAN.HOURS,
SCHEDULEPLAN.WEEKS,
SCHEDULE.MAP,
CLASSROOMS.SEATS,
CLASSROOMS.USAGE,
CLASSROOMS.JSN AS ROOMNAME,
TEACHERPLAN.TEACHERNO,
TEACHERS.NAME AS TEACHERNAME,
SCHEDULE.OEW AS OEW,
OEWOPTIONS.NAME AS WEEKNAME,
SCHEDULE.LE AS TASK,
TASKOPTIONS.NAME AS TASKNAME,
SCHEDULEPLAN.ESTIMATE,
SCHEDULE.RECNO,
SCHEDULE.UNIT,
UNITOPTIONS.NAME AS UNITNAME,
SCHEDULE.TIMER,
TIMESECTIONS.VALUE AS TIMEREQUEST,
SCHEDULE.ROOMR,
SCHEDULEPLAN.AREA,
ROOMOPTIONS.VALUE ROOMEQUIPMENT,
ROOMOPTIONS.NAME ROOMR2,
COURSES.SCHOOL,
SCHOOLS.NAME SCHOOLNAME,
CLASSES.CLASSNO +'('+RTRIM(CLASSES.CLASSNAME)+')' AS CLASSNAME,
CLASSES.CLASSNO,
TIMESECTORS.TIMEBITS as TIMES
FROM SCHEDULEPLAN
JOIN TEACHERPLAN ON SCHEDULEPLAN.RECNO=TEACHERPLAN.MAP
JOIN SCHEDULE ON (TEACHERPLAN.RECNO=SCHEDULE.MAP)
JOIN COURSEPLAN ON (SCHEDULE.COURSENO=COURSEPLAN.COURSENO AND SCHEDULE.[GROUP]=COURSEPLAN.[GROUP] AND SCHEDULE.YEAR=COURSEPLAN.YEAR AND SCHEDULE.TERM=COURSEPLAN.TERM)
JOIN CLASSES ON (COURSEPLAN.CLASSNO=CLASSES.CLASSNO)
LEFT OUTER JOIN TIMESECTORS ON SCHEDULE.TIME=TIMESECTORS.NAME
LEFT OUTER JOIN COURSES ON SCHEDULE.COURSENO=COURSES.COURSENO
LEFT OUTER JOIN SCHOOLS ON COURSES.SCHOOL=SCHOOLS.SCHOOL
LEFT OUTER JOIN TASKOPTIONS ON (SCHEDULE.LE=TASKOPTIONS.CODE)
LEFT OUTER JOIN ROOMOPTIONS ON (SCHEDULE.ROOMR=ROOMOPTIONS.NAME)
LEFT OUTER JOIN TEACHERS ON TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
LEFT OUTER JOIN TIMESECTIONS ON SCHEDULE.TIMER=TIMESECTIONS.NAME
LEFT OUTER JOIN UNITOPTIONS ON SCHEDULE.UNIT=UNITOPTIONS.CODE
LEFT OUTER JOIN CLASSROOMS ON SCHEDULE.ROOMNO=CLASSROOMS.ROOMNO
LEFT OUTER JOIN OEWOPTIONS ON SCHEDULE.OEW=OEWOPTIONS.CODE
WHERE SCHEDULEPLAN.YEAR=:YEAR AND SCHEDULEPLAN.TERM=:TERM
AND (SCHEDULEPLAN.COURSENO+SCHEDULEPLAN.[GROUP] IN (:COURSENO))
ORDER BY SCHEDULE.COURSENO,SCHEDULE.[GROUP],TEACHERPLAN.TEACHERNO*/