SELECT DISTINCT RTRIM(WHO)+PARA AS WHO,
                CLASSROOMS.JSN AS WHOSNAME,
                CAST(CLASSROOMS.RESERVED AS INT) AS RESERVED,
                TIMELIST.TYPE,
                MON,
                TUE,
                WES,
                THU,
                FRI,
                SAT,
                SUN
FROM TIMELIST
INNER JOIN CLASSROOMS ON RTRIM(TIMELIST.WHO)=RTRIM(CLASSROOMS.ROOMNO)
INNER JOIN SCHEDULE ON TIMELIST.YEAR=SCHEDULE.YEAR
  AND TIMELIST.TERM=SCHEDULE.TERM
  AND SCHEDULE.ROOMNO=RTRIM(WHO)
WHERE TIMELIST.TYPE='R'
  AND TIMELIST.YEAR=:YEAR
  AND TIMELIST.TERM=:TERM
  AND RTRIM(SCHEDULE.COURSENO+SCHEDULE.[GROUP]) IN (:COURSENO)