SELECT COUNT(*) FROM(SELECT DISTINCT S3.SCHOOL,S3.NAME SCHOOLNAME, S2.COURSENO+S2.[GROUP] AS COURSENO,C4.COURSENAME, C3.VALUE, T.HOURS,S.WEEKS, R.VALUE TYPE,T2.NAME TASKOPTIONS
	FROM CLASSROOMS C INNER JOIN SCHEDULE S 
	INNER JOIN SCHEDULEPLAN S2 ON S.YEAR = S2.YEAR AND S.TERM = S2.TERM AND S.COURSENO = S2.COURSENO AND S.[GROUP] = S2.[GROUP] 
	INNER JOIN TEACHERPLAN T ON S.YEAR = T.YEAR AND S.TERM = T.TERM AND S2.RECNO = T.MAP 
	INNER JOIN TASKOPTIONS T2 ON T.TASK = T2.CODE ON C.ROOMNO = S.ROOMNO 
	INNER JOIN ROOMOPTIONS R ON C.EQUIPMENT = R.NAME 
	INNER JOIN COURSEPLAN C2 ON S2.YEAR = C2.YEAR AND S2.TERM = C2.TERM AND S2.COURSENO = C2.COURSENO AND S2.[GROUP] = C2.[GROUP] 
	INNER JOIN COURSEAPPROACHES C3 ON C2.COURSETYPE = C3.NAME 
	INNER JOIN COURSES C4 ON S2.COURSENO = C4.COURSENO 
	INNER JOIN SCHOOLS S3 ON C4.SCHOOL = S3.SCHOOL
WHERE S2.YEAR=:YEAR AND S2.TERM=:TERM AND S2.COURSENO +S2.[GROUP] LIKE :COURSENO AND  C4.COURSENAME LIKE :COURSENAME 
AND C2.COURSETYPE LIKE :COURSETYPE AND  R.NAME LIKE :NAME AND  T.TASK='L' AND S3.SCHOOL LIKE :SCHOOL) T