SELECT COUNT(*)  
	FROM R32 R INNER JOIN COURSES C ON R.COURSENO = C.COURSENO 
		INNER JOIN STUDENTS S ON R.STUDENTNO = S.STUDENTNO 
		INNER JOIN CLASSES C3 ON C3.CLASSNO=S.CLASSNO 
	WHERE R.YEAR = :YEAR AND R.TERM = :TERM AND R.COURSENO+R.[GROUP] LIKE :COURSENO AND S.CLASSNO LIKE :CLASSNO