SELECT COURSENOGROUP,COURSENAME,COURSETYPE,SCHOOLNAME,CLASSNONAME,ATTENDENTS,
	TEACHER=STUFF((SELECT '/'+TEACHERNAME FROM 统计学期课表 V2 WHERE V2.YEAR=V.YEAR AND V2.TERM=V.TERM AND 
	V.COURSENOGROUP = V2.COURSENOGROUP AND V2.CLASSNO=V.CLASSNO FOR XML PATH('')),1,1,'')
	FROM 统计学期课表 V
	WHERE YEAR=:YEAR AND TERM=:TERM AND SCHOOL LIKE :SCHOOL
	GROUP BY COURSENOGROUP,COURSENAME,COURSETYPE,SCHOOLNAME,CLASSNO,CLASSNONAME,ATTENDENTS,[YEAR],TERM,SCHOOL