SELECT T.NAME, T.TEACHERNO,SD.NAME SEX,P.VALUE, S.NAME SCHOOLNAME
	FROM TEACHERS T INNER JOIN POSITIONS P ON T.POSITION = P.NAME INNER JOIN SCHOOLS S ON T.SCHOOL = S.SCHOOL INNER JOIN SEXCODE SD ON SD.CODE=T.SEX 
	WHERE T.SCHOOL LIKE :SCHOOL AND T.[POSITION] LIKE :POSITION
	ORDER BY SCHOOLNAME