SELECT C.CLASSNO,C.CLASSNAME,C.GRADE,C.STUDENTS,CONVERT(VARCHAR(10),C.YEAR,23) YEAR,S.NAME SCHOOLNAME,C.SCHOOL
	FROM CLASSES C INNER JOIN SCHOOLS S ON C.SCHOOL = S.SCHOOL
	WHERE C.CLASSNO LIKE :CLASSNO AND C.CLASSNAME LIKE :CLASSNAME AND C.SCHOOL LIKE :SCHOOL
