SELECT COURSENO,[GROUP],COURSENAME,COURSETYPE,EXAMTYPE,CREDITS,LHOURS,EHOURS,WEEKS,SCHOOLNAME,[TIME],ROOMVALUE,EXAM,DAYS,EMPROOM,
	ESTIMATE,ATTENDENTS,REM,
	CLASSNAME=STUFF((SELECT '/'+RTRIM(CLASSNAME) FROM 排课统计 T2 WHERE T2.YEAR=T.YEAR AND T2.TERM=T.TERM AND 
	T2.COURSENO = T.COURSENO AND T2.[GROUP] = T.[GROUP] GROUP BY T2.COURSENO,T2.[GROUP],T2.CLASSNAME FOR XML PATH('')),1,1,''),
	TEACHERNAME=STUFF((SELECT '/'+RTRIM(TEACHERNAME) FROM 排课统计 T2 WHERE T2.YEAR=T.YEAR AND T2.TERM=T.TERM AND 
	T2.COURSENO = T.COURSENO AND T2.[GROUP] = T.[GROUP] GROUP BY T2.COURSENO,T2.[GROUP],T2.TEACHERNAME FOR XML PATH('')),1,1,'')
FROM 排课统计 T
WHERE YEAR=:YEAR AND TERM=:TERM AND COURSENO LIKE :COURSENO AND [GROUP] LIKE :GROUP AND SCHOOL LIKE :SCHOOL AND TYPE LIKE :TYPE 
	AND SCHEDULED LIKE :SCHEDULED 
	AND ROOMTYPE LIKE :ROOMTYPE AND (LOCK=:BLOCK OR LOCK=:LOCK) AND (ESTIMATE <= :BESTIMATE AND ESTIMATE >= :ESTIMATE)
	AND (ATTENDENTS <= :BATTENDENTS AND ATTENDENTS >= :ATTENDENTS) AND EXAM LIKE :EXAM AND DAYS LIKE :DAYS AND CLASSNO LIKE :CLASSNO 
GROUP BY COURSENO,[GROUP],COURSENAME,COURSETYPE,EXAMTYPE,CREDITS,LHOURS,EHOURS,WEEKS,SCHOOLNAME,[TIME],ROOMVALUE,EXAM,DAYS,EMPROOM,
	ESTIMATE,ATTENDENTS,REM,YEAR,TERM,RECNO
ORDER BY SCHOOLNAME