SELECT W.[YEAR],W.TERM,W.COURSENO,W.COURSENAME,W.SCHOOLNAME,T.NAME,T.TEACHERNO,WA.WORKLOAD,W.STANDARD,W.WORKTYPENAME,S.NAME TEACHERSCHOOL
FROM WORKLOADALLOC WA 
LEFT JOIN TEACHERS T ON T.TEACHERNO=WA.TEACHERNO 
LEFT JOIN SCHOOLS S ON S.SCHOOL=T.SCHOOL 
LEFT JOIN V_WORKLOADCALC W ON W.ID=WA.CALCID 
WHERE WA.WORKLOAD > 0 AND W.WORKLOAD=W.ALLOCWORKLOAD AND W.[YEAR]=:YEAR AND W.TERM=:TERM
AND W.COURSENAME LIKE :COURSENAME AND W.COURSENO LIKE :COURSENO  AND W.SCHOOL LIKE :SCHOOL AND T.NAME LIKE :NAME AND WA.TEACHERNO LIKE :TEACHERNO
ORDER BY W.COURSENO 