SELECT STANDARDEXAMS.COURSENO AS COURSENO,
STANDARDEXAMS.EXAMNAME AS EXAMNAME,
TESTLEVEL.VALUE AS TESTLEVEL,
STANDARDEXAMS.TESTLEVEL AS TESTLEVELCODE,
STANDARDEXAMS.TESTCODE AS TESTCODE,
STANDARDEXAMS.SCHOOLCODE AS SCHOOLCODE,
COURSES.CREDITS AS CREDITS,
STANDARDEXAMS.REM AS REM,
STANDARDEXAMS.RECNO
FROM STANDARDEXAMS JOIN TESTLEVEL ON
STANDARDEXAMS.TESTLEVEL=TESTLEVEL.NAME
JOIN COURSES ON
STANDARDEXAMS.COURSENO=COURSES.COURSENO
order by courseno