SELECT count(*)
FROM EXAMAPPLIES INNER JOIN STUDENTS
ON EXAMAPPLIES.STUDENTNO=STUDENTS.STUDENTNO
LEFT OUTER JOIN SCHOOLS
ON STUDENTS.SCHOOL=SCHOOLS.SCHOOL
LEFT OUTER JOIN CLASSES ON STUDENTS.CLASSNO=CLASSES.CLASSNO
WHERE EXAMAPPLIES.MAP=:RECNO
AND EXAMAPPLIES.STUDENTNO LIKE :STUDENTNO
