SELECT STUDENTS.STUDENTNO,
STUDENTS.NAME AS STUDENTNAME,
STUDENTS.CLASSNO,CLASSES.SCHOOL,
SCHOOLS.NAME AS SCHOOLNAME,
CLASSES.CLASSNAME,
convert(varchar,STUDENTS.ENTERDATE,23) as ENTERDATE
FROM STUDENTS
LEFT JOIN CLASSES
ON STUDENTS.CLASSNO=CLASSES.CLASSNO
LEFT OUTER JOIN SCHOOLS
ON STUDENTS.SCHOOL=SCHOOLS.SCHOOL
WHERE :FIELDSNAME LIKE :FIELDSVALUE
ORDER BY STUDENTNO,SCHOOL