SELECT COUNT(EXAMAPPLIES.STUDENTNO) AS APPLIERS,SUM(EXAMNOTIFICATION.FEE) AS MONEY
FROM EXAMNOTIFICATION INNER JOIN 
EXAMAPPLIES ON EXAMNOTIFICATION.RECNO=EXAMAPPLIES.MAP
INNER JOIN STUDENTS ON EXAMAPPLIES.STUDENTNO=STUDENTS.STUDENTNO
INNER JOIN CLASSES ON CLASSES.CLASSNO=STUDENTS.CLASSNO
WHERE EXAMNOTIFICATION.RECNO=:RECNO
AND CLASSES.SCHOOL LIKE :SCHOOL
AND EXAMAPPLIES.FEE=1