SELECT count(*)
FROM EXAMAPPLIES INNER JOIN STUDENTS
ON EXAMAPPLIES.STUDENTNO=STUDENTS.STUDENTNO
INNER JOIN PERSONAL ON EXAMAPPLIES.STUDENTNO=PERSONAL.STUDENTNO
INNER JOIN CLASSES ON CLASSES.CLASSNO=STUDENTS.CLASSNO
INNER JOIN SCHOOLS ON SCHOOLS.SCHOOL=CLASSES.SCHOOL
WHERE EXAMAPPLIES.MAP=:RECNO
AND CLASSES.SCHOOL LIKE :SCHOOL
AND EXAMAPPLIES.FEE=1
