SELECT CONVERT(varchar,EXAMNOTIFICATION.DEADLINE,120) as DEADLINE,
CONVERT(varchar,EXAMNOTIFICATION.DATEOFEXAM,120) as DATEOFEXAM,
EXAMNOTIFICATION.FEE,
EXAMNOTIFICATION.REM AS NOTIFICATIONNOTE,
EXAMNOTIFICATION.RECNO,
STANDARDEXAMS.EXAMNAME,
STANDARDEXAMS.TESTCODE,
STANDARDEXAMS.REM AS EXAMREM,
CAST(EXAMNOTIFICATION.LOCK AS INT) AS LOCK
FROM EXAMNOTIFICATION
INNER JOIN STANDARDEXAMS ON
EXAMNOTIFICATION.MAP=STANDARDEXAMS.RECNO
WHERE EXAMNOTIFICATION.RECNO=:RECNO
order by STANDARDEXAMS.TESTCODE
