SELECT TESTPLAN.COURSeNO AS COURSENO , COURSES.COURSENAME , testplan.flag  ,TESTBATCH.TESTTIME ,
      TESTPLAN.ATTENDENTS , TESTPLAN.ROOMNO1 , TESTPLAN.rs1 , 
      TESTPLAN.ROOMNO2 , TESTPLAN.ROOMNO3,TESTPLAN.rs2 ,R15,'' as SL,'' as KC2,'' as KC3
FROM R32 INNER JOIN
      TESTPLAN ON R32.YEAR = TESTPLAN.year AND R32.TERM = TESTPLAN.term AND 
      R32.COURSENO + R32.[GROUP] = TESTPLAN.COURSeNO INNER JOIN
      TESTBATCH ON TESTPLAN.year = TESTBATCH.YEAR AND
      TESTPLAN.term = TESTBATCH.TERM AND
      TESTPLAN.FLAG = TESTBATCH.FLAG INNER JOIN
      COURSES ON R32.COURSENO = COURSES.COURSENO
WHERE R32.studentno =:STUDENTNO AND R32.year = :YEAR and R32.term=:TERM
order by testplan.flag