DELETE EXAMAPPLIES FROM STANDARDEXAMS
INNER JOIN EXAMNOTIFICATION ON STANDARDEXAMS.RECNO=EXAMNOTIFICATION.MAP
INNER JOIN EXAMAPPLIES ON EXAMNOTIFICATION.RECNO=EXAMAPPLIES.MAP
WHERE STANDARDEXAMS.COURSENO=:COURSENO1;

DELETE EXAMNOTIFICATION FROM STANDARDEXAMS
INNER JOIN EXAMNOTIFICATION ON STANDARDEXAMS.RECNO=EXAMNOTIFICATION.MAP
WHERE STANDARDEXAMS.COURSENO=:COURSENO2;

DELETE STANDARDEXAMS WHERE COURSENO=:COURSENO3;

DELETE COURSES WHERE COURSENO=:COURSENO4;