SELECT COUNT(*) FROM [l_VIEW_旁听生选课人数统计] L INNER JOIN
      SCHEDULEPLAN S ON 
      L.COURSENO = S.COURSENO AND 
      L.[GROUP] = S.[GROUP] AND 
      L.学年 = S.YEAR AND 
      L.学期 = S.TERM INNER JOIN
      TEACHERPLAN T ON S.YEAR = T.YEAR AND 
      S.TERM = T.TERM AND 
      S.RECNO = T.MAP INNER JOIN
      TEACHERS T2 ON T.TEACHERNO = T2.TEACHERNO INNER JOIN
      POSITIONS P ON T2.POSITION = P.NAME INNER JOIN
      SCHOOLS SCH ON T2.SCHOOL = SCH.SCHOOL
WHERE L.学年 = :YEAR AND L.学期 = :TERM 