SELECT L.课号 COURSENO, L.课名 COURSENAME, STR(L.周学时,10,1) Z_HOUR, STR(L.学分,10,1) SCORE, L.选课人数 [COUNT],STR(L.课时酬金,10,1) [SUM], 
RTRIM(T.TEACHERNO) + RTRIM(SCh.NAME) + RTRIM(T2.NAME) + RTRIM(P.VALUE)  TEACHERNAME 
FROM [l_VIEW_旁听生选课人数统计] L INNER JOIN
      SCHEDULEPLAN S ON 
      L.COURSENO = S.COURSENO AND 
      L.[GROUP] = S.[GROUP] AND 
      L.学年 = S.YEAR AND 
      L.学期 = S.TERM INNER JOIN
      TEACHERPLAN T ON S.YEAR = T.YEAR AND 
      S.TERM = T.TERM AND 
      S.RECNO = T.MAP INNER JOIN
      TEACHERS T2 ON T.TEACHERNO = T2.TEACHERNO INNER JOIN
      POSITIONS P ON T2.POSITION = P.NAME INNER JOIN
      SCHOOLS SCH ON T2.SCHOOL = SCH.SCHOOL
WHERE L.学年 = :YEAR AND L.学期 = :TERM