SELECT TEACHERS.SCHOOL,USERS.USERNAME,USERS.ROLES,SCHOOLS.NAME AS SCHOOLNAME FROM TEACHERS
JOIN USERS ON TEACHERS.TEACHERNO=USERS.TEACHERNO
JOIN SESSIONS ON USERS.USERNAME=SESSIONS.USERNAME
left join SCHOOLS on SCHOOLS.SCHOOL=TEACHERS.SCHOOL
WHERE SESSIONS.SESSIONID=:SESSIONID