SELECT C.COURSENO,C.COURSENAME,C.SCHOOL,S.NAME SCHOOLNAME,P.[VALUE] TYPE,C.STANDARD,T.WORKTYPE_NAME WORKTYPENAME,
CASE WHEN W.HOURS IS NULL THEN C.TOTAL ELSE W.HOURS END AS HOURS,
CASE WHEN W.WEEKS IS NULL THEN 17 ELSE W.WEEKS END AS WEEKS
FROM (SELECT [YEAR],TERM,COURSENO FROM SCHEDULEPLAN WHERE [YEAR]=:YEAR AND TERM=:TERM GROUP BY [YEAR],TERM,COURSENO) SP
LEFT JOIN COURSES C ON C.COURSENO=SP.COURSENO
LEFT JOIN COURSETYPEOPTIONS2 P ON P.NAME=C.TYPE2 
LEFT JOIN SCHOOLS S ON S.SCHOOL=C.SCHOOL 
LEFT JOIN WORKLOADPARAM W ON W.COURSENO=C.COURSENO
LEFT JOIN WORKLOADTYPE T ON T.WORKTYPE_CODE=W.WORKTYPE 
WHERE C.COURSENO LIKE :COURSENO AND C.COURSENAME LIKE :COURSENAME AND C.COURSENAME IS NOT NULL AND C.SCHOOL LIKE :SCHOOL