SELECT W.ID,W.[YEAR],W.TERM,W.TEACHERNO,T.NAME,T2.[VALUE] TYPE,T.SCHOOL,S.NAME SCHOOLNAME,W.WORKLOAD,W.REMARK FROM WORKLOADTEACHERS W
LEFT JOIN TEACHERS T ON T.TEACHERNO=W.TEACHERNO 
LEFT JOIN SCHOOLS S ON S.SCHOOL=T.SCHOOL 
LEFT JOIN TEACHERTYPE T2 ON T2.NAME=T.TYPE 
WHERE W.[YEAR]=:YEAR AND W.TERM=:TERM AND W.TEACHERNO LIKE :TEACHERNO AND T.NAME LIKE :NAME AND T.SCHOOL LIKE :SCHOOL
ORDER BY W.TEACHERNO