SELECT TB2.* FROM (
  SELECT dbo.GROUP_CONCAT(TB1.COURSENOGROUP,', ') AS COURSENOGROUP, dbo.GROUP_AND(TB1.TIMEBITS) AS TIMEBITS
  FROM (
    SELECT COURSENOGROUP,[DAY], dbo.GROUP_OR(dbo.GenerateTime(OEW,TIMEBITS))  AS TIMEBITS
    FROM VIEWSCHEDULE
    WHERE YEAR=:YEAR and TERM=:TERM and COURSENOGROUP IN (:COURSENOGROUPS)
    GROUP BY COURSENOGROUP,[DAY]
  ) AS TB1
  GROUP BY [DAY]
) AS TB2 where TB2.TIMEBITS>0