SELECT COURSENO,COURSETYPE,EXAMTYPE FROM VIEWSTUDENTPLANCOURSE WHERE STUDENTNO=:STUDENTNO AND COURSENO LIKE :COURSENO
/**select top 1 COURSENO, APPROACH as COURSETYPE, EXAM as EXAMTYPE from VIEWSCHEDULETABLE where COURSENOGROUP=:COURSENO**/

