SELECT 课号 as COURSENOGROUP,课名 as COURSENAME,学分 as CREDITS,周课时 as WEEKHOURS,
修课 as COURSETYPE,考核 as EXAMTYPE,听课 as APPROACH,开课学院 as SCHOOLNAME,
dbo.getone(选课标志) as FLAG,
dbo.GROUP_CONCAT_MERGE(课程安排, '<br />') as CURRICULUM,
dbo.GROUP_CONCAT_MERGE(上课教师, ', ') as TEACHERNONAME,
dbo.getone(备注) as REM
FROM VIEWSTUDENTSELECTION
WHERE YEAR=:YEAR AND TERM=:TERM AND STUDENTNO=:STUDENTNO
GROUP BY 课号,课名,学分,周课时,修课,考核,听课,开课学院
ORDER BY COURSENOGROUP
/**<#TABLE SQL=STUDENTR32.SQL PAGED=TRUE ROWS=5 GROUPED=TRUE GROUPBY=课号&课名&学分&周课时&修课&考核&听课&开课学院>**/