SELECT DISTINCT SCHEDULE.YEAR,SCHEDULE.TERM,SCHEDULE.COURSENO + SCHEDULE.[GROUP] COURSENO,COURSES.COURSENAME, SCHEDULE.ROOMNO,CLASSROOMS.JSN, CLASSROOMS.SEATS, 
        SCHEDULEPLAN.ESTIMATE 
FROM SCHEDULE INNER JOIN 
      CLASSROOMS ON SCHEDULE.ROOMNO = CLASSROOMS.ROOMNO INNER JOIN 
      COURSES ON SCHEDULE.COURSENO = COURSES.COURSENO INNER JOIN 
      SCHEDULEPLAN ON SCHEDULE.YEAR = SCHEDULEPLAN.YEAR AND 
      SCHEDULE.TERM = SCHEDULEPLAN.TERM AND 
      SCHEDULE.COURSENO = SCHEDULEPLAN.COURSENO AND 
      SCHEDULE.[GROUP] = SCHEDULEPLAN.[GROUP] 
WHERE SCHEDULE.YEAR=:YEAR AND SCHEDULE.TERM=:TERM AND CLASSROOMS.SEATS-SCHEDULEPLAN.ESTIMATE>=:RS AND SCHEDULE.ROOMNO<>'000000000' AND SCHEDULE.ROOMNO<>'L00000006'