SELECT DISTINCT V.COURSENOGROUP,V.COURSENAME,V.CREDITS,V.COURSETYPE,V.EXAMTYPE,S.ESTIMATE,ISNULL(A.AMOUNT,0) AMOUNT,V.COURSETYPENAME,
V.SCHOOLNAME,V.DAYNTIME,S.REM
	FROM VIEWSCHEDULE V LEFT OUTER JOIN SCHEDULEPLAN S ON V.RECNO = S.RECNO 
	LEFT OUTER JOIN (SELECT COUNT(*) AMOUNT,COURSENO,[GROUP],YEAR,TERM FROM R32 WHERE [YEAR]=:R_YEAR AND TERM=:R_TERM GROUP BY COURSENO,[GROUP],YEAR,TERM) A 
	ON A.[YEAR]=S.[YEAR] AND A.TERM=S.TERM AND A.COURSENO=S.COURSENO AND A.[GROUP]=S.[GROUP]
	WHERE V.YEAR = :YEAR AND V.TERM =:TERM AND S.ESTIMATE>ISNULL(A.AMOUNT,0) 
	AND V.COURSENOGROUP LIKE :COURSENOGROUP AND V.COURSETYPE LIKE :COURSETYPE AND V.CLASSNO LIKE :CLASSNO 
	AND V.SCHOOL LIKE :SCHOOL AND V.COURSETYPENAME LIKE :TYPENAME AND V.EXAMTYPE LIKE :EXAMTYPE AND V.COURSENOGROUP LIKE '08%' 