SELECT S.STUDENTNO,S.NAME,S2.CREDITS FROM STUDENTS S
LEFT OUTER JOIN(SELECT STUDENTNO,SUM(C.CREDITS) CREDITS FROM R32
  JOIN COURSES C ON R32.COURSENO=C.COURSENO WHERE YEAR=:YEAR AND TERM=:TERM GROUP BY STUDENTNO) S2 ON S.STUDENTNO=S2.STUDENTNO
WHERE S.CLASSNO=:CLASSNO  
ORDER BY S.STUDENTNO