SELECT  C2.VALUE, SUM(S.ATTENDENTS) ATTENDENTS 
	FROM COURSES C INNER JOIN SCHEDULEPLAN S ON C.COURSENO=S.COURSENO INNER JOIN COURSETYPEOPTIONS C2 ON C.TYPE = C2.NAME 
	WHERE S.YEAR=:YEAR AND S.TERM =:TERM 
	GROUP BY C2.VALUE 