SELECT DISTINCT R.COURSENO,C.COURSENAME,CAST(C.CREDITS AS CHAR) CREDITS
FROM R32 R JOIN COURSES C ON R.COURSENO=C.COURSENO
JOIN STUDENTS S ON R.STUDENTNO=S.STUDENTNO
WHERE R.YEAR=:YEAR AND R.TERM=:TERM AND S.CLASSNO=:CLASSNO
ORDER BY R.COURSENO 