SELECT COUNT(CLASSES.CLASSNO) AS ROWS
FROM CLASSES
JOIN SCHOOLS ON CLASSES.SCHOOL=SCHOOLS.SCHOOL
WHERE CLASSES.CLASSNO LIKE :CLASSNO
AND CLASSES.CLASSNAME LIKE :CLASSNAME
AND CLASSES.SCHOOL LIKE :SCHOOL