SELECT PROGRAMS.PROGRAMNO AS PROGRAMNO,
PROGRAMS.PROGNAME AS PROGRAMNAME,
PROGRAMS.REM AS REM,
PROGRAMS.TYPE AS TYPE,
PROGRAMTYPE.VALUE AS PROGRAMTYPEVALUE,
PROGRAMS.SCHOOL AS SCHOOL,
SCHOOLS.NAME AS SCHOOLNAME
FROM PROGRAMS
JOIN SCHOOLS ON PROGRAMS.SCHOOL=SCHOOLS.SCHOOL
LEFT OUTER JOIN PROGRAMTYPE ON PROGRAMS.TYPE=PROGRAMTYPE.NAME
WHERE PROGRAMS.PROGRAMNO LIKE :PROGRAMNO
AND PROGRAMS.PROGNAME LIKE :PROGRAMNAME
AND PROGRAMS.SCHOOL LIKE :SCHOOL
ORDER BY PROGRAMNO
