SELECT CLASSES.CLASSNO,
CLASSES.CLASSNAME,
CLASSES.SCHOOL,
SCHOOLS.NAME AS SCHOOLNAME
FROM CLASSES
JOIN SCHOOLS ON CLASSES.SCHOOL=SCHOOLS.SCHOOL
WHERE CLASSES.CLASSNO LIKE :CLASSNO
AND CLASSES.CLASSNAME LIKE :CLASSNAME
AND CLASSES.SCHOOL LIKE :SCHOOL
ORDER BY SCHOOL,CLASSNO