SELECT COUNT(*) AS ROWS
FROM SUBSIDIARIES
JOIN SCHOOLS ON SUBSIDIARIES.SCHOOL=SCHOOLS.SCHOOL
WHERE SUBSIDIARIES.CLASSNO LIKE :CLASSNO
AND SUBSIDIARIES.CLASSNAME LIKE :CLASSNAME
AND SUBSIDIARIES.SCHOOL LIKE :SCHOOL