SELECT COUNT(MAJORS.MAJORNO) AS ROWSID
FROM MAJORPLAN INNER JOIN
      MAJORS ON MAJORPLAN.MAP = MAJORS.ROWID INNER JOIN
      MAJORCODE ON MAJORS.MAJORNO = MAJORCODE.CODE INNER JOIN
      BRANCHCODE ON MAJORS.BRANCH = BRANCHCODE.CODE INNER JOIN
      DEGREEOPTIONS ON MAJORS.DEGREE = DEGREEOPTIONS.CODE INNER JOIN
      SCHOOLS ON MAJORS.SCHOOL = SCHOOLS.SCHOOL
WHERE MAJORS.SCHOOL LIKE (:SCHOOL) AND MAJORPLAN.YEAR = (:GRADE) AND
MAJORS.YEARS LIKE (:YEARS) AND MAJORS.MAJORNO LIKE :MAJOR