select * from (SELECT row_number() over(order by MAJORS.MAJORNO) as row,MAJORS.MAJORNO, MAJORS.YEARS AS MAJORSYEARS, MAJORS.REM AS MAJORSREM,
      MAJORPLAN.YEAR, MAJORPLAN.REM AS MAJORPLANREM, 
      MAJORCODE.NAME AS MAJORCODENAME, BRANCHCODE.NAME AS BRANCHCODENAME, 
      DEGREEOPTIONS.NAME AS DEGREEOPTIONSNAME, SCHOOLS.NAME AS SCHOOLSNAME, 
      MAJORPLAN.MCREDITS AS MAJORPLANMCREDITS, MAJORPLAN.CREDITS AS MAJORPLANCREDITS, 
      MAJORPLAN.专业方向 AS SPECIALS, MAJORPLAN.ROWID AS majorplanrowid,
      MAJORS.ROWID AS majorsrowid, MAJORS.SCHOOL AS school
FROM MAJORPLAN INNER JOIN
      MAJORS ON MAJORPLAN.MAP = MAJORS.ROWID INNER JOIN
      MAJORCODE ON MAJORS.MAJORNO = MAJORCODE.CODE INNER JOIN
      BRANCHCODE ON MAJORS.BRANCH = BRANCHCODE.CODE INNER JOIN
      DEGREEOPTIONS ON MAJORS.DEGREE = DEGREEOPTIONS.CODE INNER JOIN
      SCHOOLS ON MAJORS.SCHOOL = SCHOOLS.SCHOOL
WHERE MAJORS.SCHOOL LIKE (:SCHOOL) AND MAJORPLAN.YEAR = (:GRADE) AND
MAJORS.YEARS LIKE (:YEARS) AND MAJORS.MAJORNO LIKE :MAJOR
) as b where b.row between :start and :end