SELECT 课号 as COURSENO,课名 as COURSENAME,学分 as CREDITS,修课方式 AS APPROACHES,考核方式 AS EXAMTYPE,
周学时 as WEEKHOURS,周实验 as EXPERIMENTS,周上机 as COMPUTING,开设学年 AS YEAR,开设学期 AS TERM,
上课周次 AS WEEKS,课程类别 AS COURSETYPE,考核层次 as TESTLEVELVAL,教学大纲 as SYLLABUS
FROM VIEWR12
WHERE PROGRAMNO=:PROGRAMNO
ORDER BY YEAR,TERM
