DELETE FROM TEACHERPLAN WHERE exists (select * from SCHEDULEPLAN
WHERE RECNO=TEACHERPLAN.MAP AND SCHEDULEPLAN.YEAR=:YEAR1 AND SCHEDULEPLAN.TERM=:TERM1
AND SCHEDULEPLAN.COURSENO=:COURSENO1 AND SCHEDULEPLAN.[GROUP]=:GROUP1);

delete from courseplan where YEAR=:YEAR2 AND TERM=:TERM2 and courseno=:COURSENO2 and [group]=:GROUP2;

DELETE FROM SCHEDULEPLAN WHERE YEAR=:YEAR3 AND TERM=:TERM3 and  COURSENO=:COURSENO3 AND [GROUP]=:GROUP3 ;

delete from schedule where YEAR=:YEAR4 AND TERM=:TERM4 and COURSENO=:COURSENO4 AND [GROUP]=:GROUP4