DELETE FROM SCHEDULE WHERE YEAR=:YEAR1 AND TERM=:TERM1 AND COURSENO=:COURSENO1 AND [GROUP]=:GROUP1;

DELETE FROM R32 WHERE YEAR=:YEAR2 AND TERM=:TERM2 AND COURSENO=:COURSENO2 AND [GROUP]=:GROUP2;

DELETE FROM TESTPLAN WHERE R10=:RECNO3;

DELETE FROM TEACHERPLAN WHERE MAP=:RECNO4;

DELETE FROM SCHEDULE WHERE YEAR=:YEAR5 AND TERM=:TERM5 AND COURSENO=:COURSENO5 AND [GROUP]=:GROUP5;

DELETE FROM SCHEDULEPLAN WHERE YEAR=:YEAR6 AND TERM=:TERM6 AND COURSENO=:COURSENO6 AND [GROUP]=:GROUP6


