INSERT INTO COURSEPLAN
(YEAR,TERM,COURSENO,CLASSNO,SCHOOL,WEEKS,[GROUP],COURSETYPE,EXAMTYPE,ATTENDENTS,REM)
VALUES
(:YEAR,:TERM,:COURSENO,:CLASSNO,:SCHOOL,:WEEKS,:GROUP,:COURSETYPE,:EXAMTYPE,:ATTENDENTS,:REM)