INSERT SCHEDULE (YEAR,TERM,COURSENO,[GROUP],WEEKS,ROOMR,UNIT,LE,MAP)
SELECT SCHEDULEPLAN.YEAR,SCHEDULEPLAN.TERM,SCHEDULEPLAN.COURSENO,
				SCHEDULEPLAN.[GROUP],SCHEDULEPLAN.WEEKS,SCHEDULEPLAN.ROOMTYPE,
				TEACHERPLAN.UNIT,TEACHERPLAN.TASK,TEACHERPLAN.RECNO
FROM TEACHERPLAN
JOIN SCHEDULEPLAN ON TEACHERPLAN.MAP=SCHEDULEPLAN.RECNO
WHERE TEACHERPLAN.RECNO=:RECNO