SELECT count(*) FROM (
SELECT count(*) as NCOUNT
FROM SCHEDULEPLAN 
JOIN COURSES ON (SCHEDULEPLAN.COURSENO = COURSES.COURSENO)
JOIN COURSEPLAN ON (SCHEDULEPLAN.[YEAR]=COURSEPLAN.[YEAR] AND SCHEDULEPLAN.TERM=COURSEPLAN.TERM AND SCHEDULEPLAN.COURSENO=COURSEPLAN.COURSENO AND SCHEDULEPLAN.[GROUP]=COURSEPLAN.[GROUP])
JOIN COURSEAPPROACHES ON (COURSEPLAN.COURSETYPE=COURSEAPPROACHES.NAME)
JOIN EXAMOPTIONS ON COURSEPLAN.EXAMTYPE=EXAMOPTIONS.NAME
JOIN COURSETYPEOPTIONS2 on COURSETYPEOPTIONS2.name=COURSES.TYPE2
JOIN SCHOOLS ON COURSES.SCHOOL=SCHOOLS.SCHOOL
JOIN CLASSES ON COURSEPLAN.CLASSNO=CLASSES.CLASSNO

LEFT OUTER JOIN ROOMOPTIONS ON SCHEDULEPLAN.ROOMTYPE=ROOMOPTIONS.NAME
LEFT OUTER JOIN TIMESECTORS ON SCHEDULEPLAN.TIME=TIMESECTORS.NAME
LEFT OUTER JOIN
		(SELECT TEACHERPLAN.MAP,TEACHERPLAN.TEACHERNO,TEACHERS.SCHOOL AS SCHOOL,TEACHERS.NAME AS TEACHERNAME,TEACHERS.POSITION AS POSITION,TASKOPTIONS.NAME AS TASK,TEACHERPLAN.HOURS AS HOURS
		FROM TEACHERPLAN JOIN TEACHERS ON TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
		LEFT OUTER JOIN TASKOPTIONS ON TEACHERPLAN.TASK=TASKOPTIONS.CODE
		) AS THETEACHERS ON SCHEDULEPLAN.RECNO=THETEACHERS.MAP
LEFT OUTER JOIN (SELECT POSITIONS.VALUE AS ZC,POSITIONS.NAME AS NAME,POSITIONS.JB FROM POSITIONS) AS L_ZC ON THETEACHERS.POSITION=L_ZC.NAME

WHERE SCHEDULEPLAN.YEAR = :YEAR
AND SCHEDULEPLAN.TERM = :TERM
AND SCHEDULEPLAN.COURSENO LIKE :COURSENO
AND SCHEDULEPLAN.[GROUP] LIKE :GROUP
AND COURSES.SCHOOL LIKE :SCHOOL
AND COURSES.TYPE LIKE :COURSETYPE
AND SCHEDULEPLAN.SCHEDULED LIKE :SCHEDULED
AND SCHEDULEPLAN.ROOMTYPE LIKE :ROOMTYPE
AND COURSEPLAN.CLASSNO LIKE :CLASSNO
AND COURSEPLAN.EXAMTYPE like :EXAMTYPE
AND (SCHEDULEPLAN.ESTIMATE <= :ESTIMATEUP AND SCHEDULEPLAN.ESTIMATE >= :ESTIMATEDOWN)
AND (SCHEDULEPLAN.ATTENDENTS <= :ATTENDENTSUP AND SCHEDULEPLAN.ATTENDENTS >= :ATTENDENTSDOWN)
{$SQL.LOCK}
{$SQL.EXAM}
AND SCHEDULEPLAN.DAYS LIKE :DAYS
{$SQL.SRARCHTYPE}
GROUP BY SCHEDULEPLAN.COURSENO,SCHEDULEPLAN.[GROUP],COURSEAPPROACHES.VALUE,EXAMOPTIONS.VALUE
) as TOTALROWS