SELECT
		dbo.getOne(SCHEDULEPLAN.YEAR) AS YEAR,
    dbo.getOne(SCHEDULEPLAN.TERM) AS TERM,
    SCHEDULEPLAN.COURSENO,
    SCHEDULEPLAN.[GROUP],
		RTRIM(dbo.getOne(COURSES.COURSENAME)) AS COURSENAME,
		dbo.getOne(COURSEAPPROACHES.VALUE) AS COURSETYPEVALUE,
		dbo.getOne(EXAMOPTIONS.VALUE) AS EXAMTYPEVALUE,
		dbo.getOne(COURSES.CREDITS) AS CREDITS,
    dbo.getOne(COURSETYPEOPTIONS2.value) AS COURSETYPE,
    RTRIM(dbo.getOne(SCHOOLS.NAME)) AS SCHOOLNAME,
    dbo.getOne(SCHOOLS.SCHOOL) AS SCHOOLNO,
    dbo.getOne(SCHEDULEPLAN.ESTIMATE) AS ESTIMATE,
    dbo.getOne(SCHEDULEPLAN.ATTENDENTS) AS ATTENDENTS,
    dbo.getOne(SCHEDULEPLAN.EMPROOM) AS EMPROOM,
		dbo.getOne(TIMESECTORS.VALUE) AS TIME,
    dbo.getOne(COURSES.TOTAL) as TOTAL,
    dbo.getOne(COURSES.HOURS) as HOURS,
    dbo.getOne(SCHEDULEPLAN.LHOURS) as LHOURS,
    dbo.getOne(SCHEDULEPLAN.EHOURS) as EHOURS,
    dbo.getOne(SCHEDULEPLAN.CHOURS) as CHOURS,
    dbo.getOne(SCHEDULEPLAN.SHOURS) as SHOURS,
    dbo.getOne(SCHEDULEPLAN.ZHOURS) as ZHOURS,
    dbo.getOne(SCHEDULEPLAN.KHOURS) as KHOURS,
    dbo.getOne(SCHEDULEPLAN.WEEKS) as WEEKS,
    dbo.getOne(SCHEDULEPLAN.DAYS) as DAYS, 
    dbo.getOne(SCHEDULEPLAN.RECNO) as RECNO,
    dbo.getOne(SCHEDULEPLAN.REM) as REM,
    dbo.getOne(ROOMOPTIONS.VALUE) AS ROOMTYPE,
		dbo.getOne(CAST(SCHEDULEPLAN.EXAM  AS CHAR)) AS FINALEXAM,
		dbo.GROUP_CONCAT_MERGE('('+COURSEPLAN.CLASSNO+RTRIM(CLASSES.CLASSNAME)+')',',') AS CLASS,
		dbo.GROUP_CONCAT_MERGE(RTRIM(THETEACHERS.TEACHERNAME) +',授课任务:'+RTRIM(THETEACHERS.TASK) +',周课时:'+CAST(THETEACHERS.HOURS AS CHAR),', ') AS TEACHERTASK,
    dbo.GROUP_CONCAT_MERGE('['+RTRIM(CLASSROOMS.JSN)+'星期'+RTRIM(CAST(SCHEDULE.DAY AS CHAR))+RTRIM(TIMESECTIONS.VALUE)+RTRIM(OEWOPTIONS.NAME)+']','') AS CLASSTIME

FROM SCHEDULEPLAN 
JOIN COURSES ON (SCHEDULEPLAN.COURSENO = COURSES.COURSENO)
JOIN COURSEPLAN ON (SCHEDULEPLAN.[YEAR]=COURSEPLAN.[YEAR] AND SCHEDULEPLAN.TERM=COURSEPLAN.TERM AND SCHEDULEPLAN.COURSENO=COURSEPLAN.COURSENO AND SCHEDULEPLAN.[GROUP]=COURSEPLAN.[GROUP])
JOIN COURSEAPPROACHES ON (COURSEPLAN.COURSETYPE=COURSEAPPROACHES.NAME)
JOIN EXAMOPTIONS ON COURSEPLAN.EXAMTYPE=EXAMOPTIONS.NAME
JOIN COURSETYPEOPTIONS2 on COURSETYPEOPTIONS2.name=COURSES.TYPE2
JOIN SCHOOLS ON COURSES.SCHOOL=SCHOOLS.SCHOOL
JOIN CLASSES ON COURSEPLAN.CLASSNO=CLASSES.CLASSNO

LEFT OUTER JOIN ROOMOPTIONS ON SCHEDULEPLAN.ROOMTYPE=ROOMOPTIONS.NAME
LEFT OUTER JOIN TIMESECTORS ON SCHEDULEPLAN.TIME=TIMESECTORS.NAME
LEFT OUTER JOIN
		(SELECT TEACHERPLAN.MAP,TEACHERPLAN.TEACHERNO,TEACHERS.SCHOOL AS SCHOOL,TEACHERS.NAME AS TEACHERNAME,TEACHERS.POSITION AS POSITION,TASKOPTIONS.NAME AS TASK,TEACHERPLAN.HOURS AS HOURS
		FROM TEACHERPLAN JOIN TEACHERS ON TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
		LEFT OUTER JOIN TASKOPTIONS ON TEACHERPLAN.TASK=TASKOPTIONS.CODE
		) AS THETEACHERS ON SCHEDULEPLAN.RECNO=THETEACHERS.MAP
LEFT OUTER JOIN (SELECT POSITIONS.VALUE AS ZC,POSITIONS.NAME AS NAME,POSITIONS.JB FROM POSITIONS) AS L_ZC ON THETEACHERS.POSITION=L_ZC.NAME

LEFT OUTER JOIN SCHEDULE ON (SCHEDULEPLAN.YEAR=SCHEDULE.YEAR AND SCHEDULEPLAN.TERM=SCHEDULE.TERM AND SCHEDULEPLAN.COURSENO=SCHEDULE.COURSENO AND SCHEDULEPLAN.[GROUP]=SCHEDULE.[GROUP])
LEFT OUTER JOIN CLASSROOMS ON SCHEDULE.ROOMNO=CLASSROOMS.ROOMNO
LEFT OUTER JOIN TIMESECTIONS ON SCHEDULE.TIME=TIMESECTIONS.NAME
LEFT OUTER JOIN OEWOPTIONS ON SCHEDULE.OEW=OEWOPTIONS.CODE

WHERE SCHEDULEPLAN.YEAR = :YEAR
AND SCHEDULEPLAN.TERM = :TERM
AND SCHEDULEPLAN.COURSENO LIKE :COURSENO
AND SCHEDULEPLAN.[GROUP] LIKE :GROUP
AND COURSES.SCHOOL LIKE :SCHOOL
AND COURSES.TYPE LIKE :COURSETYPE
AND SCHEDULEPLAN.SCHEDULED LIKE :SCHEDULED
AND SCHEDULEPLAN.ROOMTYPE LIKE :ROOMTYPE
AND COURSEPLAN.CLASSNO LIKE :CLASSNO
AND COURSEPLAN.EXAMTYPE like :EXAMTYPE
AND (SCHEDULEPLAN.ESTIMATE <= :ESTIMATEUP AND SCHEDULEPLAN.ESTIMATE >= :ESTIMATEDOWN)
AND (SCHEDULEPLAN.ATTENDENTS <= :ATTENDENTSUP AND SCHEDULEPLAN.ATTENDENTS >= :ATTENDENTSDOWN)
{$SQL.LOCK}
{$SQL.EXAM}
AND SCHEDULEPLAN.DAYS LIKE :DAYS
{$SQL.SRARCHTYPE}
GROUP BY SCHEDULEPLAN.COURSENO,SCHEDULEPLAN.[GROUP]
ORDER BY COURSENO,[GROUP],COURSETYPEVALUE,EXAMTYPEVALUE