SELECT count(*) as ROWS from(
select row_number() over(order by SCHEDULE.COURSENO+SCHEDULE.[GROUP]) as row,
SCHEDULE.COURSENO+SCHEDULE.[GROUP] AS COURSENO,
COURSES.COURSENAME AS COURSENAME,
SCHOOLS.NAME SCHOOLNAME,
COURSES.SCHOOL AS SCHOOL,
'星期'+SCHEDULE.DAY+', '+TIMESECTIONS.VALUE AS TIME,
SCHEDULE.RECNO,
SCHEDULE.YEAR,
SCHEDULE.TERM,
SCHEDULE.DAY,
SCHEDULE.TIME AS TIME2,
TEACHERS.TEACHERNO,
TEACHERS.NAME AS TEACHERNAME
FROM SCHEDULE INNER JOIN TIMESECTIONS ON TIMESECTIONS.NAME=SCHEDULE.TIME
INNER JOIN COURSES ON COURSES.COURSENO=SCHEDULE.COURSENO
INNER JOIN SCHOOLS ON SCHOOLS.SCHOOL=COURSES.SCHOOL
INNER JOIN TEACHERPLAN ON SCHEDULE.MAP=TEACHERPLAN.RECNO
INNER JOIN TEACHERS ON TEACHERS.TEACHERNO=TEACHERPLAN.TEACHERNO
WHERE  SCHEDULE.YEAR=:YEAR AND SCHEDULE.TERM=:TERM AND SCHEDULE.COURSENO+SCHEDULE.[GROUP] like :COURSENO
and TEACHERS.NAME like :TEACHERNAME and COURSES.SCHOOL like :SCHOOL
) as b