SELECT COUNT(TEACHERPLAN.RECNO) AS ROWS
FROM TEACHERPLAN
INNER JOIN TEACHERS ON TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
INNER JOIN SCHOOLS ON TEACHERS.SCHOOL=SCHOOLS.SCHOOL
INNER JOIN UNITOPTIONS ON TEACHERPLAN.UNIT=UNITOPTIONS.CODE
INNER JOIN TASKOPTIONS ON TEACHERPLAN.TASK=TASKOPTIONS.CODE
INNER JOIN ZO ON TEACHERPLAN.TOSCHEDULE=CAST(ZO.NAME AS bit)
LEFT JOIN POSITIONS ON TEACHERS.POSITION=POSITIONS.NAME
WHERE TEACHERPLAN.MAP=:RECNO
AND POSITIONS.NAME is not NULL
AND TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
AND TEACHERS.SCHOOL=SCHOOLS.SCHOOL
AND TEACHERPLAN.UNIT=UNITOPTIONS.CODE
AND TEACHERPLAN.TASK=TASKOPTIONS.CODE
AND TEACHERPLAN.TOSCHEDULE=CAST(ZO.NAME AS bit)
-- SELECT COUNT(TEACHERPLAN.RECNO) AS ROWS
-- FROM TEACHERPLAN,TEACHERS,UNITOPTIONS,TASKOPTIONS,SCHOOLS,ZO,POSITIONS
-- WHERE TEACHERPLAN.MAP=:RECNO
-- AND TEACHERPLAN.TEACHERNO=TEACHERS.TEACHERNO
-- AND TEACHERS.SCHOOL=SCHOOLS.SCHOOL
-- AND TEACHERPLAN.UNIT=UNITOPTIONS.CODE
-- AND TEACHERPLAN.TASK=TASKOPTIONS.CODE
-- AND TEACHERPLAN.TOSCHEDULE=CAST(ZO.NAME AS bit)
-- AND TEACHERS.POSITION=POSITIONS.NAME