SELECT SCHEDULEPLAN.YEAR,
SCHEDULEPLAN.TERM,
SCHEDULEPLAN.COURSENO,
SCHEDULEPLAN.[GROUP],
SCHEDULEPLAN.ESTIMATE,
SCHEDULEPLAN.TEACHER,
SCHEDULEPLAN.ATTENDENTS,
SCHEDULEPLAN.EMPROOM,
SCHEDULEPLAN.ROOMTYPE,
SCHEDULEPLAN.TIME,
SCHEDULEPLAN.SCHEDULED,
SCHEDULEPLAN.KHOURS,
SCHEDULEPLAN.CHOURS,
SCHEDULEPLAN.LHOURS,
SCHEDULEPLAN.EHOURS,
SCHEDULEPLAN.SHOURS,
SCHEDULEPLAN.ZHOURS,
SCHEDULEPLAN.EBATCH,
SCHEDULEPLAN.PRIORITY,
SCHEDULEPLAN.WEEKS,
SCHEDULEPLAN.degree,
SCHEDULEPLAN.OLDESTIMATE,
CAST(SCHEDULEPLAN.LOCK AS INT) AS LOCK,
CAST(SCHEDULEPLAN.EXAM AS INT) AS EXAM,
SCHEDULEPLAN.DAYS,
SCHEDULEPLAN.AREA,
SCHEDULEPLAN.RECNO,
SCHEDULEPLAN.REM,
CAST(SCHEDULEPLAN.SEATSLOCK AS INT) AS SEATSLOCK,
SCHOOLS.NAME AS SCHOOLNAME,
COURSES.COURSENAME,
COURSES.SCHOOL AS SCHOOL 
FROM SCHEDULEPLAN,COURSES,SCHOOLS
WHERE   (SCHEDULEPLAN.COURSENO=COURSES.COURSENO)
   AND  (COURSES.SCHOOL=SCHOOLS.SCHOOL)
   AND  (SCHEDULEPLAN.YEAR LIKE :YEAR)
   AND  (SCHEDULEPLAN.TERM = :TERM)
   AND  (SCHEDULEPLAN.COURSENO LIKE :COURSENO)
   AND  (SCHEDULEPLAN.[GROUP] LIKE :GROUP)