UPDATE COURSEPLAN SET ATTENDENTS=:NATTENDENTS1,[GROUP]=dbo.fn_10to36(:NGROUP1)
WHERE YEAR=:YEAR1 AND TERM=:TERM1 AND COURSENO=:COURSENO1 AND CLASSNO=:CLASSNO1 AND [GROUP]=:GROUP1;

INSERT INTO COURSEPLAN (YEAR,TERM,COURSENO,CLASSNO,SCHOOL,WEEKS,[GROUP],COURSETYPE,EXAMTYPE,ATTENDENTS)
VALUES(:YEAR2,:TERM2,:COURSENO2,:CLASSNO2,:SCHOOL2,:WEEKS2,dbo.fn_10to36(:GROUP2),:COURSETYPE2,:EXAMTYPE2,:ATTENDENTS2)
