INSERT INTO SCHEDULECHANGE(TEACHERNO,REASON,YEAR,TERM,COURSENO,SCHOOL,WEEK,DAY,TIME,SUBMIT,SUBMITDATE,Addtion)
SELECT TEACHERS.TEACHERNO, :REASON, SCHEDULE.YEAR, SCHEDULE.TERM, SCHEDULE.COURSENO+SCHEDULE.[GROUP] AS COURSENO,
	COURSES.SCHOOL AS SCHOOL, :WEEK, SCHEDULE.DAY, SCHEDULE.TIME AS TIME2, :USERNAME, getdate(),:ADDTION
FROM SCHEDULE INNER JOIN TIMESECTIONS ON TIMESECTIONS.NAME=SCHEDULE.TIME
INNER JOIN COURSES ON COURSES.COURSENO=SCHEDULE.COURSENO
INNER JOIN SCHOOLS ON SCHOOLS.SCHOOL=COURSES.SCHOOL
INNER JOIN TEACHERPLAN ON SCHEDULE.MAP=TEACHERPLAN.RECNO
INNER JOIN TEACHERS ON TEACHERS.TEACHERNO=TEACHERPLAN.TEACHERNO
WHERE  SCHEDULE.RECNO IN (:RECNOS) AND COURSES.SCHOOL like :SCHOOL