DELETE FROM TESTPLAN WHERE YEAR=:YEAR1 AND TERM=:TERM1;

DELETE FROM TEACHERPLAN WHERE YEAR=:YEAR2 AND TERM=:TERM2;

DELETE FROM SCHEDULE WHERE YEAR=:YEAR3 AND TERM=:TERM3;

DELETE FROM SCHEDULEPLAN WHERE YEAR=:YEAR4 AND TERM=:TERM4;

