INSERT INTO SCHEDULEPLAN([YEAR], TERM, COURSENO, [GROUP],ESTIMATE, ROOMTYPE, LHOURS, EHOURS,CHOURS,  SHOURS, KHOURS,ZHOURS, WEEKS, EXAM)
(SELECT distinct [YEAR], TERM, COURSEPLAN.COURSENO, [GROUP], SUM(ATTENDENTS),
 CASE [TYPE]   WHEN 'D' THEN 'B'  WHEN 'F' THEN 'P'  WHEN 'B' THEN 'B'  ELSE 'U'  END AS ROOMTYPE,
 (COURSES.HOURS-COURSES.EXPERIMENTS-COURSES.COMPUTING-COURSES.KHOURS-COURSES.SHOURS-COURSES.ZHOURS) AS LHOURS,
 COURSES.EXPERIMENTS,  COURSES.COMPUTING, COURSES.SHOURS, COURSES.KHOURS, COURSES.ZHOURS,  COURSEPLAN.WEEKS,
 CASE [EXAMTYPE]  WHEN 'T' THEN 1  WHEN 'E' THEN 0  ELSE 0  END AS EXAM
 FROM COURSEPLAN, COURSES
 WHERE COURSES.COURSENO = COURSEPLAN.COURSENO AND YEAR =:YEAR5 AND TERM =:TERM5
 GROUP BY year,term,courseplan.courseno,[group],courses.hours,type,courses.experiments,courses.computing,
 courses.shours,courses.khours,courses.zhours,courseplan.weeks,courseplan.examtype);