UPDATE SCHEDULEPLAN
SET ESTIMATE=:ESTIMATE,EBATCH=:EBATCH,degree=:degree,EMPROOM=:EMPROOM,ROOMTYPE=:ROOMTYPE,
REM=:REM,SEATSLOCK=:SEATSLOCK,TIME=:TIME,SCHEDULED=:SCHEDULED,LHOURS=:LHOURS,
EHOURS=:EHOURS,CHOURS=:CHOURS,KHOURS=:KHOURS,SHOURS=:SHOURS,ZHOURS=:ZHOURS,
LOCK=:LOCK,EXAM=:EXAM,DAYS=:DAYS,AREA=:AREA
WHERE RECNO=:RECNO