UPDATE SCHEDULEPLAN SET [GROUP]=:NGROUP1,WEEKS=:NWEEKS1 WHERE YEAR=:YEAR1 AND TERM=:TERM1 AND COURSENO=:COURSENO1 AND [GROUP]=:GROUP1;

UPDATE SCHEDULE SET [GROUP]=:NGROUP2,WEEKS=:NWEEKS2 WHERE YEAR=:YEAR2 AND TERM=:TERM2 AND COURSENO=:COURSENO2 AND [GROUP]=:GROUP2;

UPDATE R32 SET [GROUP]=:NGROUP3 WHERE YEAR=:YEAR3 AND TERM=:TERM3 AND COURSENO=:COURSENO3 AND [GROUP]=:GROUP3;

UPDATE COURSEPLAN set CLASSNO=:NCLASSNO4,ATTENDENTS=:NATTENDENTS4,REM=:NREM4,WEEKS=:NWEEKS4,[GROUP]=:NGROUP4,COURSETYPE=:NCOURSETYPE4,EXAMTYPE=:NEXAMTYPE4
WHERE YEAR=:YEAR4 and TERM=:TERM4 and COURSENO=:COURSENO4 and CLASSNO=:CLASSNO4 and [GROUP]=:GROUP4


