SELECT C.RECNO,C.COURSENO,C.[GROUP],C2.COURSENAME,C3.[VALUE],C.COURSETYPE,C4.CLASSNAME,C.CLASSNO,C.ATTENDENTS,S.NAME SCHOOLNAME,C.SCHOOL,S2.RECNO S_RECNO,
(SELECT TOP 1.NAME FROM TEACHERPLAN T LEFT JOIN TEACHERS T2 ON T.TEACHERNO=T2.TEACHERNO WHERE T.MAP=S2.RECNO) TEACHERNAME,C.[YEAR],C.TERM,
(SELECT COUNT(*) FROM (SELECT DISTINCT t.TEACHERNO FROM TEACHERPLAN T LEFT JOIN TEACHERS T2 ON T.TEACHERNO=T2.TEACHERNO WHERE T.MAP=S2.RECNO and T2.NAME!='000000') T3) TEACHERNUM,
(SELECT COUNT(*) FROM BOOKAPPLY B WHERE B.COURSENO=C.COURSENO AND B.[GROUP]=C.[GROUP] AND B.[YEAR]=C.[YEAR] AND B.TERM=C.TERM AND B.SCHOOL=C.SCHOOL AND B.CLASSNO=C.CLASSNO) APPLYNUM 
	FROM COURSEPLAN C LEFT JOIN COURSES C2 ON C.COURSENO=C2.COURSENO 
	LEFT JOIN COURSEAPPROACHES C3 ON C.COURSETYPE=C3.NAME 
	LEFT JOIN CLASSES C4 ON C.CLASSNO=C4.CLASSNO 
	LEFT JOIN SCHOOLS S ON S.SCHOOL=C.SCHOOL 
	LEFT JOIN SCHEDULEPLAN S2 ON C.COURSENO = S2.COURSENO AND C.[GROUP]=S2.[GROUP] AND C.[YEAR]=S2.[YEAR] AND C.TERM=S2.TERM 
WHERE C.[YEAR]=:YEAR AND C.TERM=:TERM AND C3.NAME LIKE :COURSETYPE AND C.COURSENO+C.[GROUP] LIKE :COURSENO AND C2.COURSENAME LIKE :COURSENAME  AND C.SCHOOL LIKE :SCHOOL
AND C.CLASSNO LIKE :CLASSNO