SELECT COUNT(*) AS ROWS
FROM R28 JOIN PROGRAMS
ON R28.PROGRAMNO=PROGRAMS.PROGRAMNO
JOIN SCHOOLS ON PROGRAMS.SCHOOL=SCHOOLS.SCHOOL
LEFT OUTER JOIN PROGRAMTYPE ON PROGRAMS.TYPE=PROGRAMTYPE.NAME
WHERE R28.STUDENTNO=:STUDENTNO
