SELECT COUNT(*) FROM (SELECT  DISTINCT S.SCHOOL,S.NAME SCHOOLNAME,T.TEACHERNO,T.NAME TEACHERNAME, S2.NAME SEX,P.VALUE 
	FROM TEACHERS T INNER JOIN SCHOOLS S ON T.SCHOOL = S.SCHOOL 
	INNER JOIN POSITIONS P ON T.POSITION = P.NAME
  INNER JOIN SEXCODE S2 ON T.SEX=S2.CODE AND S.SCHOOL LIKE :SCHOOL AND (T.POSITION = 'A' OR T.POSITION = 'C') AND TEACHERNO NOT IN
  (SELECT TEACHERNO FROM TEACHERPLAN WHERE YEAR = :YEAR AND TERM LIKE :TERM)) T