SELECT  distinct S2.NAME SCHOOLNAME,S.COURSENO+S.[GROUP] COURSENO,C.COURSENAME, S.LHOURS+S.EHOURS HOURS,S.WEEKS, C2.VALUE
	FROM SCHEDULEPLAN S INNER JOIN COURSES C ON S.COURSENO = C.COURSENO 
	INNER JOIN SCHOOLS S2 ON C.SCHOOL = S2.SCHOOL 
	INNER JOIN COURSETYPEOPTIONS C2 ON C.TYPE = C2.NAME
	WHERE S.[YEAR]=:YEAR AND S.TERM=:TERM AND S.COURSENO+S.[GROUP] LIKE :COURSENO AND COURSENAME LIKE :COURSENAME AND C.SCHOOL LIKE :SCHOOL AND C.TYPE<>'H'
	ORDER BY COURSENO