SELECT DISTINCT SCHEDULEPLAN.YEAR,SCHEDULEPLAN.TERM, SCHOOLS.SCHOOL,SCHOOLS.NAME SCHOOLNAME,TEACHERS.TEACHERNO,TEACHERS.NAME TEACHERNAME,
	POSITIONS.VALUE, POSITIONS.JB, POSITIONS.ZhuJiangZhiGe,SCHEDULEPLAN.COURSENO+SCHEDULEPLAN.[GROUP] COURSENO,COURSES.COURSENAME COURSENAME, 
  COURSETYPEOPTIONS.VALUE TYPE, COURSES.CREDITS, COURSES.HOURS,COURSES.EXPERIMENTS, COURSES.COMPUTING 
FROM COURSES INNER JOIN
  SCHEDULEPLAN ON 
  COURSES.COURSENO = SCHEDULEPLAN.COURSENO INNER JOIN
  TEACHERPLAN ON SCHEDULEPLAN.YEAR = TEACHERPLAN.YEAR AND 
  SCHEDULEPLAN.TERM = TEACHERPLAN.TERM AND 
  SCHEDULEPLAN.RECNO = TEACHERPLAN.MAP INNER JOIN
  TEACHERS ON TEACHERPLAN.TEACHERNO = TEACHERS.TEACHERNO INNER JOIN
  POSITIONS ON TEACHERS.POSITION = POSITIONS.NAME INNER JOIN
  SCHOOLS ON TEACHERS.SCHOOL = SCHOOLS.SCHOOL INNER JOIN
  COURSETYPEOPTIONS ON COURSES.TYPE = COURSETYPEOPTIONS.NAME
WHERE SCHEDULEPLAN.YEAR = :YEAR AND  SCHEDULEPLAN.TERM =:TERM 
  and TEACHERPLAN.teacherno like :TEACHERNO and teachers.name like :TEACHERNAME
  and POSITIONS.name like :POSITIONS and POSITIONS.JB like :JB
  and POSITIONS.ZhuJiangZhiGe like :ZhuJiangZhiGe and TEACHERS.SCHOOL like :SCHOOL